// Code generated by ent, DO NOT EDIT.

package nubantransfer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Toflex/directory_v2/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldDeletedAt, v))
}

// RecipientAccountName applies equality check predicate on the "recipient_account_name" field. It's identical to RecipientAccountNameEQ.
func RecipientAccountName(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldRecipientAccountName, v))
}

// RecipientAccountNumber applies equality check predicate on the "recipient_account_number" field. It's identical to RecipientAccountNumberEQ.
func RecipientAccountNumber(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldRecipientAccountNumber, v))
}

// SenderAccountName applies equality check predicate on the "sender_account_name" field. It's identical to SenderAccountNameEQ.
func SenderAccountName(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSenderAccountName, v))
}

// SenderAccountNumber applies equality check predicate on the "sender_account_number" field. It's identical to SenderAccountNumberEQ.
func SenderAccountNumber(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSenderAccountNumber, v))
}

// SenderBankName applies equality check predicate on the "sender_bank_name" field. It's identical to SenderBankNameEQ.
func SenderBankName(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSenderBankName, v))
}

// SenderBankCode applies equality check predicate on the "sender_bank_code" field. It's identical to SenderBankCodeEQ.
func SenderBankCode(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSenderBankCode, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldAmount, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSessionID, v))
}

// ProviderReference applies equality check predicate on the "provider_reference" field. It's identical to ProviderReferenceEQ.
func ProviderReference(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldProviderReference, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldProvider, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotNull(FieldDeletedAt))
}

// RecipientAccountNameEQ applies the EQ predicate on the "recipient_account_name" field.
func RecipientAccountNameEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldRecipientAccountName, v))
}

// RecipientAccountNameNEQ applies the NEQ predicate on the "recipient_account_name" field.
func RecipientAccountNameNEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldRecipientAccountName, v))
}

// RecipientAccountNameIn applies the In predicate on the "recipient_account_name" field.
func RecipientAccountNameIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldRecipientAccountName, vs...))
}

// RecipientAccountNameNotIn applies the NotIn predicate on the "recipient_account_name" field.
func RecipientAccountNameNotIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldRecipientAccountName, vs...))
}

// RecipientAccountNameGT applies the GT predicate on the "recipient_account_name" field.
func RecipientAccountNameGT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldRecipientAccountName, v))
}

// RecipientAccountNameGTE applies the GTE predicate on the "recipient_account_name" field.
func RecipientAccountNameGTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldRecipientAccountName, v))
}

// RecipientAccountNameLT applies the LT predicate on the "recipient_account_name" field.
func RecipientAccountNameLT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldRecipientAccountName, v))
}

// RecipientAccountNameLTE applies the LTE predicate on the "recipient_account_name" field.
func RecipientAccountNameLTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldRecipientAccountName, v))
}

// RecipientAccountNameContains applies the Contains predicate on the "recipient_account_name" field.
func RecipientAccountNameContains(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContains(FieldRecipientAccountName, v))
}

// RecipientAccountNameHasPrefix applies the HasPrefix predicate on the "recipient_account_name" field.
func RecipientAccountNameHasPrefix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasPrefix(FieldRecipientAccountName, v))
}

// RecipientAccountNameHasSuffix applies the HasSuffix predicate on the "recipient_account_name" field.
func RecipientAccountNameHasSuffix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasSuffix(FieldRecipientAccountName, v))
}

// RecipientAccountNameEqualFold applies the EqualFold predicate on the "recipient_account_name" field.
func RecipientAccountNameEqualFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldRecipientAccountName, v))
}

// RecipientAccountNameContainsFold applies the ContainsFold predicate on the "recipient_account_name" field.
func RecipientAccountNameContainsFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldRecipientAccountName, v))
}

// RecipientAccountNumberEQ applies the EQ predicate on the "recipient_account_number" field.
func RecipientAccountNumberEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberNEQ applies the NEQ predicate on the "recipient_account_number" field.
func RecipientAccountNumberNEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberIn applies the In predicate on the "recipient_account_number" field.
func RecipientAccountNumberIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldRecipientAccountNumber, vs...))
}

// RecipientAccountNumberNotIn applies the NotIn predicate on the "recipient_account_number" field.
func RecipientAccountNumberNotIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldRecipientAccountNumber, vs...))
}

// RecipientAccountNumberGT applies the GT predicate on the "recipient_account_number" field.
func RecipientAccountNumberGT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberGTE applies the GTE predicate on the "recipient_account_number" field.
func RecipientAccountNumberGTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberLT applies the LT predicate on the "recipient_account_number" field.
func RecipientAccountNumberLT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberLTE applies the LTE predicate on the "recipient_account_number" field.
func RecipientAccountNumberLTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberContains applies the Contains predicate on the "recipient_account_number" field.
func RecipientAccountNumberContains(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContains(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberHasPrefix applies the HasPrefix predicate on the "recipient_account_number" field.
func RecipientAccountNumberHasPrefix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasPrefix(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberHasSuffix applies the HasSuffix predicate on the "recipient_account_number" field.
func RecipientAccountNumberHasSuffix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasSuffix(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberEqualFold applies the EqualFold predicate on the "recipient_account_number" field.
func RecipientAccountNumberEqualFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldRecipientAccountNumber, v))
}

// RecipientAccountNumberContainsFold applies the ContainsFold predicate on the "recipient_account_number" field.
func RecipientAccountNumberContainsFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldRecipientAccountNumber, v))
}

// SenderAccountNameEQ applies the EQ predicate on the "sender_account_name" field.
func SenderAccountNameEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSenderAccountName, v))
}

// SenderAccountNameNEQ applies the NEQ predicate on the "sender_account_name" field.
func SenderAccountNameNEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldSenderAccountName, v))
}

// SenderAccountNameIn applies the In predicate on the "sender_account_name" field.
func SenderAccountNameIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldSenderAccountName, vs...))
}

// SenderAccountNameNotIn applies the NotIn predicate on the "sender_account_name" field.
func SenderAccountNameNotIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldSenderAccountName, vs...))
}

// SenderAccountNameGT applies the GT predicate on the "sender_account_name" field.
func SenderAccountNameGT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldSenderAccountName, v))
}

// SenderAccountNameGTE applies the GTE predicate on the "sender_account_name" field.
func SenderAccountNameGTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldSenderAccountName, v))
}

// SenderAccountNameLT applies the LT predicate on the "sender_account_name" field.
func SenderAccountNameLT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldSenderAccountName, v))
}

// SenderAccountNameLTE applies the LTE predicate on the "sender_account_name" field.
func SenderAccountNameLTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldSenderAccountName, v))
}

// SenderAccountNameContains applies the Contains predicate on the "sender_account_name" field.
func SenderAccountNameContains(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContains(FieldSenderAccountName, v))
}

// SenderAccountNameHasPrefix applies the HasPrefix predicate on the "sender_account_name" field.
func SenderAccountNameHasPrefix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasPrefix(FieldSenderAccountName, v))
}

// SenderAccountNameHasSuffix applies the HasSuffix predicate on the "sender_account_name" field.
func SenderAccountNameHasSuffix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasSuffix(FieldSenderAccountName, v))
}

// SenderAccountNameEqualFold applies the EqualFold predicate on the "sender_account_name" field.
func SenderAccountNameEqualFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldSenderAccountName, v))
}

// SenderAccountNameContainsFold applies the ContainsFold predicate on the "sender_account_name" field.
func SenderAccountNameContainsFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldSenderAccountName, v))
}

// SenderAccountNumberEQ applies the EQ predicate on the "sender_account_number" field.
func SenderAccountNumberEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSenderAccountNumber, v))
}

// SenderAccountNumberNEQ applies the NEQ predicate on the "sender_account_number" field.
func SenderAccountNumberNEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldSenderAccountNumber, v))
}

// SenderAccountNumberIn applies the In predicate on the "sender_account_number" field.
func SenderAccountNumberIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldSenderAccountNumber, vs...))
}

// SenderAccountNumberNotIn applies the NotIn predicate on the "sender_account_number" field.
func SenderAccountNumberNotIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldSenderAccountNumber, vs...))
}

// SenderAccountNumberGT applies the GT predicate on the "sender_account_number" field.
func SenderAccountNumberGT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldSenderAccountNumber, v))
}

// SenderAccountNumberGTE applies the GTE predicate on the "sender_account_number" field.
func SenderAccountNumberGTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldSenderAccountNumber, v))
}

// SenderAccountNumberLT applies the LT predicate on the "sender_account_number" field.
func SenderAccountNumberLT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldSenderAccountNumber, v))
}

// SenderAccountNumberLTE applies the LTE predicate on the "sender_account_number" field.
func SenderAccountNumberLTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldSenderAccountNumber, v))
}

// SenderAccountNumberContains applies the Contains predicate on the "sender_account_number" field.
func SenderAccountNumberContains(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContains(FieldSenderAccountNumber, v))
}

// SenderAccountNumberHasPrefix applies the HasPrefix predicate on the "sender_account_number" field.
func SenderAccountNumberHasPrefix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasPrefix(FieldSenderAccountNumber, v))
}

// SenderAccountNumberHasSuffix applies the HasSuffix predicate on the "sender_account_number" field.
func SenderAccountNumberHasSuffix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasSuffix(FieldSenderAccountNumber, v))
}

// SenderAccountNumberEqualFold applies the EqualFold predicate on the "sender_account_number" field.
func SenderAccountNumberEqualFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldSenderAccountNumber, v))
}

// SenderAccountNumberContainsFold applies the ContainsFold predicate on the "sender_account_number" field.
func SenderAccountNumberContainsFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldSenderAccountNumber, v))
}

// SenderBankNameEQ applies the EQ predicate on the "sender_bank_name" field.
func SenderBankNameEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSenderBankName, v))
}

// SenderBankNameNEQ applies the NEQ predicate on the "sender_bank_name" field.
func SenderBankNameNEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldSenderBankName, v))
}

// SenderBankNameIn applies the In predicate on the "sender_bank_name" field.
func SenderBankNameIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldSenderBankName, vs...))
}

// SenderBankNameNotIn applies the NotIn predicate on the "sender_bank_name" field.
func SenderBankNameNotIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldSenderBankName, vs...))
}

// SenderBankNameGT applies the GT predicate on the "sender_bank_name" field.
func SenderBankNameGT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldSenderBankName, v))
}

// SenderBankNameGTE applies the GTE predicate on the "sender_bank_name" field.
func SenderBankNameGTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldSenderBankName, v))
}

// SenderBankNameLT applies the LT predicate on the "sender_bank_name" field.
func SenderBankNameLT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldSenderBankName, v))
}

// SenderBankNameLTE applies the LTE predicate on the "sender_bank_name" field.
func SenderBankNameLTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldSenderBankName, v))
}

// SenderBankNameContains applies the Contains predicate on the "sender_bank_name" field.
func SenderBankNameContains(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContains(FieldSenderBankName, v))
}

// SenderBankNameHasPrefix applies the HasPrefix predicate on the "sender_bank_name" field.
func SenderBankNameHasPrefix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasPrefix(FieldSenderBankName, v))
}

// SenderBankNameHasSuffix applies the HasSuffix predicate on the "sender_bank_name" field.
func SenderBankNameHasSuffix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasSuffix(FieldSenderBankName, v))
}

// SenderBankNameEqualFold applies the EqualFold predicate on the "sender_bank_name" field.
func SenderBankNameEqualFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldSenderBankName, v))
}

// SenderBankNameContainsFold applies the ContainsFold predicate on the "sender_bank_name" field.
func SenderBankNameContainsFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldSenderBankName, v))
}

// SenderBankCodeEQ applies the EQ predicate on the "sender_bank_code" field.
func SenderBankCodeEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSenderBankCode, v))
}

// SenderBankCodeNEQ applies the NEQ predicate on the "sender_bank_code" field.
func SenderBankCodeNEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldSenderBankCode, v))
}

// SenderBankCodeIn applies the In predicate on the "sender_bank_code" field.
func SenderBankCodeIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldSenderBankCode, vs...))
}

// SenderBankCodeNotIn applies the NotIn predicate on the "sender_bank_code" field.
func SenderBankCodeNotIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldSenderBankCode, vs...))
}

// SenderBankCodeGT applies the GT predicate on the "sender_bank_code" field.
func SenderBankCodeGT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldSenderBankCode, v))
}

// SenderBankCodeGTE applies the GTE predicate on the "sender_bank_code" field.
func SenderBankCodeGTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldSenderBankCode, v))
}

// SenderBankCodeLT applies the LT predicate on the "sender_bank_code" field.
func SenderBankCodeLT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldSenderBankCode, v))
}

// SenderBankCodeLTE applies the LTE predicate on the "sender_bank_code" field.
func SenderBankCodeLTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldSenderBankCode, v))
}

// SenderBankCodeContains applies the Contains predicate on the "sender_bank_code" field.
func SenderBankCodeContains(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContains(FieldSenderBankCode, v))
}

// SenderBankCodeHasPrefix applies the HasPrefix predicate on the "sender_bank_code" field.
func SenderBankCodeHasPrefix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasPrefix(FieldSenderBankCode, v))
}

// SenderBankCodeHasSuffix applies the HasSuffix predicate on the "sender_bank_code" field.
func SenderBankCodeHasSuffix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasSuffix(FieldSenderBankCode, v))
}

// SenderBankCodeEqualFold applies the EqualFold predicate on the "sender_bank_code" field.
func SenderBankCodeEqualFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldSenderBankCode, v))
}

// SenderBankCodeContainsFold applies the ContainsFold predicate on the "sender_bank_code" field.
func SenderBankCodeContainsFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldSenderBankCode, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldAmount, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldSessionID, v))
}

// ProviderReferenceEQ applies the EQ predicate on the "provider_reference" field.
func ProviderReferenceEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldProviderReference, v))
}

// ProviderReferenceNEQ applies the NEQ predicate on the "provider_reference" field.
func ProviderReferenceNEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldProviderReference, v))
}

// ProviderReferenceIn applies the In predicate on the "provider_reference" field.
func ProviderReferenceIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldProviderReference, vs...))
}

// ProviderReferenceNotIn applies the NotIn predicate on the "provider_reference" field.
func ProviderReferenceNotIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldProviderReference, vs...))
}

// ProviderReferenceGT applies the GT predicate on the "provider_reference" field.
func ProviderReferenceGT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldProviderReference, v))
}

// ProviderReferenceGTE applies the GTE predicate on the "provider_reference" field.
func ProviderReferenceGTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldProviderReference, v))
}

// ProviderReferenceLT applies the LT predicate on the "provider_reference" field.
func ProviderReferenceLT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldProviderReference, v))
}

// ProviderReferenceLTE applies the LTE predicate on the "provider_reference" field.
func ProviderReferenceLTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldProviderReference, v))
}

// ProviderReferenceContains applies the Contains predicate on the "provider_reference" field.
func ProviderReferenceContains(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContains(FieldProviderReference, v))
}

// ProviderReferenceHasPrefix applies the HasPrefix predicate on the "provider_reference" field.
func ProviderReferenceHasPrefix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasPrefix(FieldProviderReference, v))
}

// ProviderReferenceHasSuffix applies the HasSuffix predicate on the "provider_reference" field.
func ProviderReferenceHasSuffix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasSuffix(FieldProviderReference, v))
}

// ProviderReferenceEqualFold applies the EqualFold predicate on the "provider_reference" field.
func ProviderReferenceEqualFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldProviderReference, v))
}

// ProviderReferenceContainsFold applies the ContainsFold predicate on the "provider_reference" field.
func ProviderReferenceContainsFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldProviderReference, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.FieldContainsFold(FieldProvider, v))
}

// HasTransaction applies the HasEdge predicate on the "transaction" edge.
func HasTransaction() predicate.NubanTransfer {
	return predicate.NubanTransfer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TransactionTable, TransactionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionWith applies the HasEdge predicate on the "transaction" edge with a given conditions (other predicates).
func HasTransactionWith(preds ...predicate.Transaction) predicate.NubanTransfer {
	return predicate.NubanTransfer(func(s *sql.Selector) {
		step := newTransactionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NubanTransfer) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NubanTransfer) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NubanTransfer) predicate.NubanTransfer {
	return predicate.NubanTransfer(sql.NotPredicates(p))
}
