FROM golang:1.26.4

WORKDIR /usr/src/migration

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download
RUN go install ariga.io/atlas/cmd/atlas@latest && cp /go/bin/atlas /usr/local/bin/atlas

COPY . .
RUN go build -v -o /usr/local/bin/app ./cmd/migration/migration.go

CMD ["/usr/local/bin/app"]
