FROM golang:1.26.4

WORKDIR /usr/src/migration

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download

RUN apk --no-cache add ca-certificates libc6-compat curl \ 
    && curl -sSf https://atlasgo.sh | sh

COPY . .
RUN go build -v -o /usr/local/bin/app ./cmd/migration/migration.go

CMD ["/usr/local/bin/app"]
