"""
Creates a new wallet.

Example:

mutation {
  addWallet(
    currencyCode: "NGN"
    walletType: "MAIN"
  ) {
    id
    currency
    type
    availableBalance
  }
}
"""

enum WalletType {
  TREASURY
}

type Wallet {
    available_balance: Float!
    ledger_balance: Float!
    holding_balance: Float!
    id: String!
    currency: String!
    active: Boolean!
    is_fiat: Boolean!
}

input WalletFilter {
    is_fiat: Boolean!
}

extend type Query {
  business_wallets(wallet_type: WalletType!=TREASURY, filter: WalletFilter): [Wallet!]!  @hasRole (role: ADMIN)
  business_wallet(currencyCode: String!, wallet_type: WalletType!=TREASURY): Wallet  @hasRole (role: ADMIN)
}

extend type Mutation {
  add_business_wallet(currency_code: String!, wallet_type: WalletType!=TREASURY): Wallet!  @hasRole (role: ADMIN)
}