package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/Toflex/directory_v2/graph/model"
)

// GetBusiness is the resolver for the getBusiness field.
func (r *queryResolver) GetBusiness(ctx context.Context, id string) (*model.Business, error) {
	panic(fmt.Errorf("not implemented: GetBusiness - getBusiness"))
}

// FindBusiness is the resolver for the findBusiness field.
func (r *queryResolver) FindBusiness(ctx context.Context, name *string, service *string, limit *int32) ([]*model.SearchBusiness, error) {
	panic(fmt.Errorf("not implemented: FindBusiness - findBusiness"))
}
