package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/Toflex/directory_v2/graph/model"
)

// RequestVerification is the resolver for the requestVerification field.
func (r *mutationResolver) RequestVerification(ctx context.Context, input model.VerificationPayload) (*model.Verification, error) {
	panic(fmt.Errorf("not implemented: RequestVerification - requestVerification"))
}
