// Code generated by ent, DO NOT EDIT.

package nubanstaticaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Toflex/directory_v2/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldProvider, v))
}

// ProviderReference applies equality check predicate on the "provider_reference" field. It's identical to ProviderReferenceEQ.
func ProviderReference(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldProviderReference, v))
}

// AccountNumber applies equality check predicate on the "account_number" field. It's identical to AccountNumberEQ.
func AccountNumber(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldAccountNumber, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldAccountName, v))
}

// BankName applies equality check predicate on the "bank_name" field. It's identical to BankNameEQ.
func BankName(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldBankName, v))
}

// BankCode applies equality check predicate on the "bank_code" field. It's identical to BankCodeEQ.
func BankCode(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldBankCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotNull(FieldDeletedAt))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderReferenceEQ applies the EQ predicate on the "provider_reference" field.
func ProviderReferenceEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldProviderReference, v))
}

// ProviderReferenceNEQ applies the NEQ predicate on the "provider_reference" field.
func ProviderReferenceNEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldProviderReference, v))
}

// ProviderReferenceIn applies the In predicate on the "provider_reference" field.
func ProviderReferenceIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldProviderReference, vs...))
}

// ProviderReferenceNotIn applies the NotIn predicate on the "provider_reference" field.
func ProviderReferenceNotIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldProviderReference, vs...))
}

// ProviderReferenceGT applies the GT predicate on the "provider_reference" field.
func ProviderReferenceGT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldProviderReference, v))
}

// ProviderReferenceGTE applies the GTE predicate on the "provider_reference" field.
func ProviderReferenceGTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldProviderReference, v))
}

// ProviderReferenceLT applies the LT predicate on the "provider_reference" field.
func ProviderReferenceLT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldProviderReference, v))
}

// ProviderReferenceLTE applies the LTE predicate on the "provider_reference" field.
func ProviderReferenceLTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldProviderReference, v))
}

// ProviderReferenceContains applies the Contains predicate on the "provider_reference" field.
func ProviderReferenceContains(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContains(FieldProviderReference, v))
}

// ProviderReferenceHasPrefix applies the HasPrefix predicate on the "provider_reference" field.
func ProviderReferenceHasPrefix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasPrefix(FieldProviderReference, v))
}

// ProviderReferenceHasSuffix applies the HasSuffix predicate on the "provider_reference" field.
func ProviderReferenceHasSuffix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasSuffix(FieldProviderReference, v))
}

// ProviderReferenceEqualFold applies the EqualFold predicate on the "provider_reference" field.
func ProviderReferenceEqualFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEqualFold(FieldProviderReference, v))
}

// ProviderReferenceContainsFold applies the ContainsFold predicate on the "provider_reference" field.
func ProviderReferenceContainsFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContainsFold(FieldProviderReference, v))
}

// AccountNumberEQ applies the EQ predicate on the "account_number" field.
func AccountNumberEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldAccountNumber, v))
}

// AccountNumberNEQ applies the NEQ predicate on the "account_number" field.
func AccountNumberNEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldAccountNumber, v))
}

// AccountNumberIn applies the In predicate on the "account_number" field.
func AccountNumberIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldAccountNumber, vs...))
}

// AccountNumberNotIn applies the NotIn predicate on the "account_number" field.
func AccountNumberNotIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldAccountNumber, vs...))
}

// AccountNumberGT applies the GT predicate on the "account_number" field.
func AccountNumberGT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldAccountNumber, v))
}

// AccountNumberGTE applies the GTE predicate on the "account_number" field.
func AccountNumberGTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldAccountNumber, v))
}

// AccountNumberLT applies the LT predicate on the "account_number" field.
func AccountNumberLT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldAccountNumber, v))
}

// AccountNumberLTE applies the LTE predicate on the "account_number" field.
func AccountNumberLTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldAccountNumber, v))
}

// AccountNumberContains applies the Contains predicate on the "account_number" field.
func AccountNumberContains(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContains(FieldAccountNumber, v))
}

// AccountNumberHasPrefix applies the HasPrefix predicate on the "account_number" field.
func AccountNumberHasPrefix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasPrefix(FieldAccountNumber, v))
}

// AccountNumberHasSuffix applies the HasSuffix predicate on the "account_number" field.
func AccountNumberHasSuffix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasSuffix(FieldAccountNumber, v))
}

// AccountNumberEqualFold applies the EqualFold predicate on the "account_number" field.
func AccountNumberEqualFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEqualFold(FieldAccountNumber, v))
}

// AccountNumberContainsFold applies the ContainsFold predicate on the "account_number" field.
func AccountNumberContainsFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContainsFold(FieldAccountNumber, v))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContainsFold(FieldAccountName, v))
}

// BankNameEQ applies the EQ predicate on the "bank_name" field.
func BankNameEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldBankName, v))
}

// BankNameNEQ applies the NEQ predicate on the "bank_name" field.
func BankNameNEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldBankName, v))
}

// BankNameIn applies the In predicate on the "bank_name" field.
func BankNameIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldBankName, vs...))
}

// BankNameNotIn applies the NotIn predicate on the "bank_name" field.
func BankNameNotIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldBankName, vs...))
}

// BankNameGT applies the GT predicate on the "bank_name" field.
func BankNameGT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldBankName, v))
}

// BankNameGTE applies the GTE predicate on the "bank_name" field.
func BankNameGTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldBankName, v))
}

// BankNameLT applies the LT predicate on the "bank_name" field.
func BankNameLT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldBankName, v))
}

// BankNameLTE applies the LTE predicate on the "bank_name" field.
func BankNameLTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldBankName, v))
}

// BankNameContains applies the Contains predicate on the "bank_name" field.
func BankNameContains(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContains(FieldBankName, v))
}

// BankNameHasPrefix applies the HasPrefix predicate on the "bank_name" field.
func BankNameHasPrefix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasPrefix(FieldBankName, v))
}

// BankNameHasSuffix applies the HasSuffix predicate on the "bank_name" field.
func BankNameHasSuffix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasSuffix(FieldBankName, v))
}

// BankNameEqualFold applies the EqualFold predicate on the "bank_name" field.
func BankNameEqualFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEqualFold(FieldBankName, v))
}

// BankNameContainsFold applies the ContainsFold predicate on the "bank_name" field.
func BankNameContainsFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContainsFold(FieldBankName, v))
}

// BankCodeEQ applies the EQ predicate on the "bank_code" field.
func BankCodeEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldBankCode, v))
}

// BankCodeNEQ applies the NEQ predicate on the "bank_code" field.
func BankCodeNEQ(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldBankCode, v))
}

// BankCodeIn applies the In predicate on the "bank_code" field.
func BankCodeIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldBankCode, vs...))
}

// BankCodeNotIn applies the NotIn predicate on the "bank_code" field.
func BankCodeNotIn(vs ...string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldBankCode, vs...))
}

// BankCodeGT applies the GT predicate on the "bank_code" field.
func BankCodeGT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGT(FieldBankCode, v))
}

// BankCodeGTE applies the GTE predicate on the "bank_code" field.
func BankCodeGTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldGTE(FieldBankCode, v))
}

// BankCodeLT applies the LT predicate on the "bank_code" field.
func BankCodeLT(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLT(FieldBankCode, v))
}

// BankCodeLTE applies the LTE predicate on the "bank_code" field.
func BankCodeLTE(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldLTE(FieldBankCode, v))
}

// BankCodeContains applies the Contains predicate on the "bank_code" field.
func BankCodeContains(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContains(FieldBankCode, v))
}

// BankCodeHasPrefix applies the HasPrefix predicate on the "bank_code" field.
func BankCodeHasPrefix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasPrefix(FieldBankCode, v))
}

// BankCodeHasSuffix applies the HasSuffix predicate on the "bank_code" field.
func BankCodeHasSuffix(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldHasSuffix(FieldBankCode, v))
}

// BankCodeEqualFold applies the EqualFold predicate on the "bank_code" field.
func BankCodeEqualFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEqualFold(FieldBankCode, v))
}

// BankCodeContainsFold applies the ContainsFold predicate on the "bank_code" field.
func BankCodeContainsFold(v string) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldContainsFold(FieldBankCode, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.FieldNotIn(FieldState, vs...))
}

// HasWallet applies the HasEdge predicate on the "wallet" edge.
func HasWallet() predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WalletTable, WalletColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWalletWith applies the HasEdge predicate on the "wallet" edge with a given conditions (other predicates).
func HasWalletWith(preds ...predicate.Wallet) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(func(s *sql.Selector) {
		step := newWalletStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NubanStaticAccount) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NubanStaticAccount) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NubanStaticAccount) predicate.NubanStaticAccount {
	return predicate.NubanStaticAccount(sql.NotPredicates(p))
}
