// Code generated by ent, DO NOT EDIT.

package stablecoinwallet

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Toflex/directory_v2/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldDeletedAt, v))
}

// Coin applies equality check predicate on the "coin" field. It's identical to CoinEQ.
func Coin(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldCoin, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldNetwork, v))
}

// NetworkID applies equality check predicate on the "network_id" field. It's identical to NetworkIDEQ.
func NetworkID(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldNetworkID, v))
}

// CoinID applies equality check predicate on the "coin_id" field. It's identical to CoinIDEQ.
func CoinID(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldCoinID, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldAddress, v))
}

// ProviderReference applies equality check predicate on the "provider_reference" field. It's identical to ProviderReferenceEQ.
func ProviderReference(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldProviderReference, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldProvider, v))
}

// Disabled applies equality check predicate on the "disabled" field. It's identical to DisabledEQ.
func Disabled(v bool) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldDisabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotNull(FieldDeletedAt))
}

// CoinEQ applies the EQ predicate on the "coin" field.
func CoinEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldCoin, v))
}

// CoinNEQ applies the NEQ predicate on the "coin" field.
func CoinNEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldCoin, v))
}

// CoinIn applies the In predicate on the "coin" field.
func CoinIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldCoin, vs...))
}

// CoinNotIn applies the NotIn predicate on the "coin" field.
func CoinNotIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldCoin, vs...))
}

// CoinGT applies the GT predicate on the "coin" field.
func CoinGT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldCoin, v))
}

// CoinGTE applies the GTE predicate on the "coin" field.
func CoinGTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldCoin, v))
}

// CoinLT applies the LT predicate on the "coin" field.
func CoinLT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldCoin, v))
}

// CoinLTE applies the LTE predicate on the "coin" field.
func CoinLTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldCoin, v))
}

// CoinContains applies the Contains predicate on the "coin" field.
func CoinContains(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContains(FieldCoin, v))
}

// CoinHasPrefix applies the HasPrefix predicate on the "coin" field.
func CoinHasPrefix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasPrefix(FieldCoin, v))
}

// CoinHasSuffix applies the HasSuffix predicate on the "coin" field.
func CoinHasSuffix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasSuffix(FieldCoin, v))
}

// CoinEqualFold applies the EqualFold predicate on the "coin" field.
func CoinEqualFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEqualFold(FieldCoin, v))
}

// CoinContainsFold applies the ContainsFold predicate on the "coin" field.
func CoinContainsFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContainsFold(FieldCoin, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContainsFold(FieldNetwork, v))
}

// NetworkIDEQ applies the EQ predicate on the "network_id" field.
func NetworkIDEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldNetworkID, v))
}

// NetworkIDNEQ applies the NEQ predicate on the "network_id" field.
func NetworkIDNEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldNetworkID, v))
}

// NetworkIDIn applies the In predicate on the "network_id" field.
func NetworkIDIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldNetworkID, vs...))
}

// NetworkIDNotIn applies the NotIn predicate on the "network_id" field.
func NetworkIDNotIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldNetworkID, vs...))
}

// NetworkIDGT applies the GT predicate on the "network_id" field.
func NetworkIDGT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldNetworkID, v))
}

// NetworkIDGTE applies the GTE predicate on the "network_id" field.
func NetworkIDGTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldNetworkID, v))
}

// NetworkIDLT applies the LT predicate on the "network_id" field.
func NetworkIDLT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldNetworkID, v))
}

// NetworkIDLTE applies the LTE predicate on the "network_id" field.
func NetworkIDLTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldNetworkID, v))
}

// NetworkIDContains applies the Contains predicate on the "network_id" field.
func NetworkIDContains(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContains(FieldNetworkID, v))
}

// NetworkIDHasPrefix applies the HasPrefix predicate on the "network_id" field.
func NetworkIDHasPrefix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasPrefix(FieldNetworkID, v))
}

// NetworkIDHasSuffix applies the HasSuffix predicate on the "network_id" field.
func NetworkIDHasSuffix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasSuffix(FieldNetworkID, v))
}

// NetworkIDEqualFold applies the EqualFold predicate on the "network_id" field.
func NetworkIDEqualFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEqualFold(FieldNetworkID, v))
}

// NetworkIDContainsFold applies the ContainsFold predicate on the "network_id" field.
func NetworkIDContainsFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContainsFold(FieldNetworkID, v))
}

// CoinIDEQ applies the EQ predicate on the "coin_id" field.
func CoinIDEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldCoinID, v))
}

// CoinIDNEQ applies the NEQ predicate on the "coin_id" field.
func CoinIDNEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldCoinID, v))
}

// CoinIDIn applies the In predicate on the "coin_id" field.
func CoinIDIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldCoinID, vs...))
}

// CoinIDNotIn applies the NotIn predicate on the "coin_id" field.
func CoinIDNotIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldCoinID, vs...))
}

// CoinIDGT applies the GT predicate on the "coin_id" field.
func CoinIDGT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldCoinID, v))
}

// CoinIDGTE applies the GTE predicate on the "coin_id" field.
func CoinIDGTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldCoinID, v))
}

// CoinIDLT applies the LT predicate on the "coin_id" field.
func CoinIDLT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldCoinID, v))
}

// CoinIDLTE applies the LTE predicate on the "coin_id" field.
func CoinIDLTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldCoinID, v))
}

// CoinIDContains applies the Contains predicate on the "coin_id" field.
func CoinIDContains(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContains(FieldCoinID, v))
}

// CoinIDHasPrefix applies the HasPrefix predicate on the "coin_id" field.
func CoinIDHasPrefix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasPrefix(FieldCoinID, v))
}

// CoinIDHasSuffix applies the HasSuffix predicate on the "coin_id" field.
func CoinIDHasSuffix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasSuffix(FieldCoinID, v))
}

// CoinIDEqualFold applies the EqualFold predicate on the "coin_id" field.
func CoinIDEqualFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEqualFold(FieldCoinID, v))
}

// CoinIDContainsFold applies the ContainsFold predicate on the "coin_id" field.
func CoinIDContainsFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContainsFold(FieldCoinID, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContainsFold(FieldAddress, v))
}

// ProviderReferenceEQ applies the EQ predicate on the "provider_reference" field.
func ProviderReferenceEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldProviderReference, v))
}

// ProviderReferenceNEQ applies the NEQ predicate on the "provider_reference" field.
func ProviderReferenceNEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldProviderReference, v))
}

// ProviderReferenceIn applies the In predicate on the "provider_reference" field.
func ProviderReferenceIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldProviderReference, vs...))
}

// ProviderReferenceNotIn applies the NotIn predicate on the "provider_reference" field.
func ProviderReferenceNotIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldProviderReference, vs...))
}

// ProviderReferenceGT applies the GT predicate on the "provider_reference" field.
func ProviderReferenceGT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldProviderReference, v))
}

// ProviderReferenceGTE applies the GTE predicate on the "provider_reference" field.
func ProviderReferenceGTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldProviderReference, v))
}

// ProviderReferenceLT applies the LT predicate on the "provider_reference" field.
func ProviderReferenceLT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldProviderReference, v))
}

// ProviderReferenceLTE applies the LTE predicate on the "provider_reference" field.
func ProviderReferenceLTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldProviderReference, v))
}

// ProviderReferenceContains applies the Contains predicate on the "provider_reference" field.
func ProviderReferenceContains(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContains(FieldProviderReference, v))
}

// ProviderReferenceHasPrefix applies the HasPrefix predicate on the "provider_reference" field.
func ProviderReferenceHasPrefix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasPrefix(FieldProviderReference, v))
}

// ProviderReferenceHasSuffix applies the HasSuffix predicate on the "provider_reference" field.
func ProviderReferenceHasSuffix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasSuffix(FieldProviderReference, v))
}

// ProviderReferenceEqualFold applies the EqualFold predicate on the "provider_reference" field.
func ProviderReferenceEqualFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEqualFold(FieldProviderReference, v))
}

// ProviderReferenceContainsFold applies the ContainsFold predicate on the "provider_reference" field.
func ProviderReferenceContainsFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContainsFold(FieldProviderReference, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldContainsFold(FieldProvider, v))
}

// DisabledEQ applies the EQ predicate on the "disabled" field.
func DisabledEQ(v bool) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldEQ(FieldDisabled, v))
}

// DisabledNEQ applies the NEQ predicate on the "disabled" field.
func DisabledNEQ(v bool) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.FieldNEQ(FieldDisabled, v))
}

// HasWallet applies the HasEdge predicate on the "wallet" edge.
func HasWallet() predicate.StablecoinWallet {
	return predicate.StablecoinWallet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WalletTable, WalletColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWalletWith applies the HasEdge predicate on the "wallet" edge with a given conditions (other predicates).
func HasWalletWith(preds ...predicate.Wallet) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(func(s *sql.Selector) {
		step := newWalletStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCurrency applies the HasEdge predicate on the "currency" edge.
func HasCurrency() predicate.StablecoinWallet {
	return predicate.StablecoinWallet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CurrencyTable, CurrencyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCurrencyWith applies the HasEdge predicate on the "currency" edge with a given conditions (other predicates).
func HasCurrencyWith(preds ...predicate.Currency) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(func(s *sql.Selector) {
		step := newCurrencyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStablecoinNetworks applies the HasEdge predicate on the "stablecoin_networks" edge.
func HasStablecoinNetworks() predicate.StablecoinWallet {
	return predicate.StablecoinWallet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StablecoinNetworksTable, StablecoinNetworksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStablecoinNetworksWith applies the HasEdge predicate on the "stablecoin_networks" edge with a given conditions (other predicates).
func HasStablecoinNetworksWith(preds ...predicate.StablecoinNetwork) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(func(s *sql.Selector) {
		step := newStablecoinNetworksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStablecoinDeposits applies the HasEdge predicate on the "stablecoin_deposits" edge.
func HasStablecoinDeposits() predicate.StablecoinWallet {
	return predicate.StablecoinWallet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StablecoinDepositsTable, StablecoinDepositsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStablecoinDepositsWith applies the HasEdge predicate on the "stablecoin_deposits" edge with a given conditions (other predicates).
func HasStablecoinDepositsWith(preds ...predicate.StablecoinDeposit) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(func(s *sql.Selector) {
		step := newStablecoinDepositsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StablecoinWallet) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StablecoinWallet) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StablecoinWallet) predicate.StablecoinWallet {
	return predicate.StablecoinWallet(sql.NotPredicates(p))
}
