// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Toflex/directory_v2/ent/business"
	"github.com/Toflex/directory_v2/ent/user"
)

// Business is the model entity for the Business schema.
type Business struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// About holds the value of the "about" field.
	About string `json:"about,omitempty"`
	// Logo holds the value of the "logo" field.
	Logo string `json:"logo,omitempty"`
	// CoverImage holds the value of the "cover_image" field.
	CoverImage string `json:"cover_image,omitempty"`
	// RegisteredBy holds the value of the "registered_by" field.
	RegisteredBy *string `json:"registered_by,omitempty"`
	// CountryOfIncorporation holds the value of the "country_of_incorporation" field.
	CountryOfIncorporation *string `json:"country_of_incorporation,omitempty"`
	// DateOfIncorporation holds the value of the "date_of_incorporation" field.
	DateOfIncorporation *string `json:"date_of_incorporation,omitempty"`
	// RegistrationNumber holds the value of the "registration_number" field.
	RegistrationNumber *string `json:"registration_number,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Website holds the value of the "website" field.
	Website string `json:"website,omitempty"`
	// OnSite holds the value of the "on_site" field.
	OnSite bool `json:"on_site,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Live holds the value of the "live" field.
	Live bool `json:"live,omitempty"`
	// Disabled holds the value of the "disabled" field.
	Disabled bool `json:"disabled,omitempty"`
	// DisabledAt holds the value of the "disabled_at" field.
	DisabledAt time.Time `json:"disabled_at,omitempty"`
	// DisableReason holds the value of the "disable_reason" field.
	DisableReason string `json:"disable_reason,omitempty"`
	// VerificationStatus holds the value of the "verification_status" field.
	VerificationStatus business.VerificationStatus `json:"verification_status,omitempty"`
	// Verified holds the value of the "verified" field.
	Verified bool `json:"verified,omitempty"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt time.Time `json:"verified_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BusinessQuery when eager-loading is set.
	Edges        BusinessEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BusinessEdges holds the relations/edges for other nodes in the graph.
type BusinessEdges struct {
	// Socials holds the value of the socials edge.
	Socials []*Social `json:"socials,omitempty"`
	// Services holds the value of the services edge.
	Services []*BusinessServices `json:"services,omitempty"`
	// Manages holds the value of the manages edge.
	Manages []*Manager `json:"manages,omitempty"`
	// RegisteredByUser holds the value of the registered_by_user edge.
	RegisteredByUser *User `json:"registered_by_user,omitempty"`
	// Verifications holds the value of the verifications edge.
	Verifications []*Verification `json:"verifications,omitempty"`
	// RequestVerifications holds the value of the request_verifications edge.
	RequestVerifications []*RequestVerification `json:"request_verifications,omitempty"`
	// BusinessDocuments holds the value of the business_documents edge.
	BusinessDocuments []*BusinessDocument `json:"business_documents,omitempty"`
	// Locations holds the value of the locations edge.
	Locations []*BusinessLocation `json:"locations,omitempty"`
	// KybMessages holds the value of the kyb_messages edge.
	KybMessages []*KYBMessage `json:"kyb_messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [9]bool
}

// SocialsOrErr returns the Socials value or an error if the edge
// was not loaded in eager-loading.
func (e BusinessEdges) SocialsOrErr() ([]*Social, error) {
	if e.loadedTypes[0] {
		return e.Socials, nil
	}
	return nil, &NotLoadedError{edge: "socials"}
}

// ServicesOrErr returns the Services value or an error if the edge
// was not loaded in eager-loading.
func (e BusinessEdges) ServicesOrErr() ([]*BusinessServices, error) {
	if e.loadedTypes[1] {
		return e.Services, nil
	}
	return nil, &NotLoadedError{edge: "services"}
}

// ManagesOrErr returns the Manages value or an error if the edge
// was not loaded in eager-loading.
func (e BusinessEdges) ManagesOrErr() ([]*Manager, error) {
	if e.loadedTypes[2] {
		return e.Manages, nil
	}
	return nil, &NotLoadedError{edge: "manages"}
}

// RegisteredByUserOrErr returns the RegisteredByUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BusinessEdges) RegisteredByUserOrErr() (*User, error) {
	if e.RegisteredByUser != nil {
		return e.RegisteredByUser, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "registered_by_user"}
}

// VerificationsOrErr returns the Verifications value or an error if the edge
// was not loaded in eager-loading.
func (e BusinessEdges) VerificationsOrErr() ([]*Verification, error) {
	if e.loadedTypes[4] {
		return e.Verifications, nil
	}
	return nil, &NotLoadedError{edge: "verifications"}
}

// RequestVerificationsOrErr returns the RequestVerifications value or an error if the edge
// was not loaded in eager-loading.
func (e BusinessEdges) RequestVerificationsOrErr() ([]*RequestVerification, error) {
	if e.loadedTypes[5] {
		return e.RequestVerifications, nil
	}
	return nil, &NotLoadedError{edge: "request_verifications"}
}

// BusinessDocumentsOrErr returns the BusinessDocuments value or an error if the edge
// was not loaded in eager-loading.
func (e BusinessEdges) BusinessDocumentsOrErr() ([]*BusinessDocument, error) {
	if e.loadedTypes[6] {
		return e.BusinessDocuments, nil
	}
	return nil, &NotLoadedError{edge: "business_documents"}
}

// LocationsOrErr returns the Locations value or an error if the edge
// was not loaded in eager-loading.
func (e BusinessEdges) LocationsOrErr() ([]*BusinessLocation, error) {
	if e.loadedTypes[7] {
		return e.Locations, nil
	}
	return nil, &NotLoadedError{edge: "locations"}
}

// KybMessagesOrErr returns the KybMessages value or an error if the edge
// was not loaded in eager-loading.
func (e BusinessEdges) KybMessagesOrErr() ([]*KYBMessage, error) {
	if e.loadedTypes[8] {
		return e.KybMessages, nil
	}
	return nil, &NotLoadedError{edge: "kyb_messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Business) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case business.FieldOnSite, business.FieldActive, business.FieldLive, business.FieldDisabled, business.FieldVerified:
			values[i] = new(sql.NullBool)
		case business.FieldID, business.FieldCategory, business.FieldName, business.FieldAbout, business.FieldLogo, business.FieldCoverImage, business.FieldRegisteredBy, business.FieldCountryOfIncorporation, business.FieldDateOfIncorporation, business.FieldRegistrationNumber, business.FieldEmail, business.FieldWebsite, business.FieldDisableReason, business.FieldVerificationStatus:
			values[i] = new(sql.NullString)
		case business.FieldCreatedAt, business.FieldUpdatedAt, business.FieldDeletedAt, business.FieldDisabledAt, business.FieldVerifiedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Business fields.
func (b *Business) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case business.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				b.ID = value.String
			}
		case business.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				b.CreatedAt = value.Time
			}
		case business.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				b.UpdatedAt = value.Time
			}
		case business.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				b.DeletedAt = new(time.Time)
				*b.DeletedAt = value.Time
			}
		case business.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				b.Category = value.String
			}
		case business.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				b.Name = value.String
			}
		case business.FieldAbout:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field about", values[i])
			} else if value.Valid {
				b.About = value.String
			}
		case business.FieldLogo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo", values[i])
			} else if value.Valid {
				b.Logo = value.String
			}
		case business.FieldCoverImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_image", values[i])
			} else if value.Valid {
				b.CoverImage = value.String
			}
		case business.FieldRegisteredBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registered_by", values[i])
			} else if value.Valid {
				b.RegisteredBy = new(string)
				*b.RegisteredBy = value.String
			}
		case business.FieldCountryOfIncorporation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country_of_incorporation", values[i])
			} else if value.Valid {
				b.CountryOfIncorporation = new(string)
				*b.CountryOfIncorporation = value.String
			}
		case business.FieldDateOfIncorporation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date_of_incorporation", values[i])
			} else if value.Valid {
				b.DateOfIncorporation = new(string)
				*b.DateOfIncorporation = value.String
			}
		case business.FieldRegistrationNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registration_number", values[i])
			} else if value.Valid {
				b.RegistrationNumber = new(string)
				*b.RegistrationNumber = value.String
			}
		case business.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				b.Email = value.String
			}
		case business.FieldWebsite:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field website", values[i])
			} else if value.Valid {
				b.Website = value.String
			}
		case business.FieldOnSite:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field on_site", values[i])
			} else if value.Valid {
				b.OnSite = value.Bool
			}
		case business.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				b.Active = value.Bool
			}
		case business.FieldLive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field live", values[i])
			} else if value.Valid {
				b.Live = value.Bool
			}
		case business.FieldDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field disabled", values[i])
			} else if value.Valid {
				b.Disabled = value.Bool
			}
		case business.FieldDisabledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field disabled_at", values[i])
			} else if value.Valid {
				b.DisabledAt = value.Time
			}
		case business.FieldDisableReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field disable_reason", values[i])
			} else if value.Valid {
				b.DisableReason = value.String
			}
		case business.FieldVerificationStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field verification_status", values[i])
			} else if value.Valid {
				b.VerificationStatus = business.VerificationStatus(value.String)
			}
		case business.FieldVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified", values[i])
			} else if value.Valid {
				b.Verified = value.Bool
			}
		case business.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				b.VerifiedAt = value.Time
			}
		default:
			b.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Business.
// This includes values selected through modifiers, order, etc.
func (b *Business) Value(name string) (ent.Value, error) {
	return b.selectValues.Get(name)
}

// QuerySocials queries the "socials" edge of the Business entity.
func (b *Business) QuerySocials() *SocialQuery {
	return NewBusinessClient(b.config).QuerySocials(b)
}

// QueryServices queries the "services" edge of the Business entity.
func (b *Business) QueryServices() *BusinessServicesQuery {
	return NewBusinessClient(b.config).QueryServices(b)
}

// QueryManages queries the "manages" edge of the Business entity.
func (b *Business) QueryManages() *ManagerQuery {
	return NewBusinessClient(b.config).QueryManages(b)
}

// QueryRegisteredByUser queries the "registered_by_user" edge of the Business entity.
func (b *Business) QueryRegisteredByUser() *UserQuery {
	return NewBusinessClient(b.config).QueryRegisteredByUser(b)
}

// QueryVerifications queries the "verifications" edge of the Business entity.
func (b *Business) QueryVerifications() *VerificationQuery {
	return NewBusinessClient(b.config).QueryVerifications(b)
}

// QueryRequestVerifications queries the "request_verifications" edge of the Business entity.
func (b *Business) QueryRequestVerifications() *RequestVerificationQuery {
	return NewBusinessClient(b.config).QueryRequestVerifications(b)
}

// QueryBusinessDocuments queries the "business_documents" edge of the Business entity.
func (b *Business) QueryBusinessDocuments() *BusinessDocumentQuery {
	return NewBusinessClient(b.config).QueryBusinessDocuments(b)
}

// QueryLocations queries the "locations" edge of the Business entity.
func (b *Business) QueryLocations() *BusinessLocationQuery {
	return NewBusinessClient(b.config).QueryLocations(b)
}

// QueryKybMessages queries the "kyb_messages" edge of the Business entity.
func (b *Business) QueryKybMessages() *KYBMessageQuery {
	return NewBusinessClient(b.config).QueryKybMessages(b)
}

// Update returns a builder for updating this Business.
// Note that you need to call Business.Unwrap() before calling this method if this Business
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Business) Update() *BusinessUpdateOne {
	return NewBusinessClient(b.config).UpdateOne(b)
}

// Unwrap unwraps the Business entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Business) Unwrap() *Business {
	_tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Business is not a transactional entity")
	}
	b.config.driver = _tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Business) String() string {
	var builder strings.Builder
	builder.WriteString("Business(")
	builder.WriteString(fmt.Sprintf("id=%v, ", b.ID))
	builder.WriteString("created_at=")
	builder.WriteString(b.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(b.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := b.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(b.Category)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(b.Name)
	builder.WriteString(", ")
	builder.WriteString("about=")
	builder.WriteString(b.About)
	builder.WriteString(", ")
	builder.WriteString("logo=")
	builder.WriteString(b.Logo)
	builder.WriteString(", ")
	builder.WriteString("cover_image=")
	builder.WriteString(b.CoverImage)
	builder.WriteString(", ")
	if v := b.RegisteredBy; v != nil {
		builder.WriteString("registered_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := b.CountryOfIncorporation; v != nil {
		builder.WriteString("country_of_incorporation=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := b.DateOfIncorporation; v != nil {
		builder.WriteString("date_of_incorporation=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := b.RegistrationNumber; v != nil {
		builder.WriteString("registration_number=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(b.Email)
	builder.WriteString(", ")
	builder.WriteString("website=")
	builder.WriteString(b.Website)
	builder.WriteString(", ")
	builder.WriteString("on_site=")
	builder.WriteString(fmt.Sprintf("%v", b.OnSite))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", b.Active))
	builder.WriteString(", ")
	builder.WriteString("live=")
	builder.WriteString(fmt.Sprintf("%v", b.Live))
	builder.WriteString(", ")
	builder.WriteString("disabled=")
	builder.WriteString(fmt.Sprintf("%v", b.Disabled))
	builder.WriteString(", ")
	builder.WriteString("disabled_at=")
	builder.WriteString(b.DisabledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("disable_reason=")
	builder.WriteString(b.DisableReason)
	builder.WriteString(", ")
	builder.WriteString("verification_status=")
	builder.WriteString(fmt.Sprintf("%v", b.VerificationStatus))
	builder.WriteString(", ")
	builder.WriteString("verified=")
	builder.WriteString(fmt.Sprintf("%v", b.Verified))
	builder.WriteString(", ")
	builder.WriteString("verified_at=")
	builder.WriteString(b.VerifiedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Businesses is a parsable slice of Business.
type Businesses []*Business
