// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Toflex/directory_v2/ent/business"
	"github.com/Toflex/directory_v2/ent/businessdocument"
	"github.com/Toflex/directory_v2/ent/businesslocation"
	"github.com/Toflex/directory_v2/ent/businessservices"
	"github.com/Toflex/directory_v2/ent/kybmessage"
	"github.com/Toflex/directory_v2/ent/manager"
	"github.com/Toflex/directory_v2/ent/predicate"
	"github.com/Toflex/directory_v2/ent/requestverification"
	"github.com/Toflex/directory_v2/ent/social"
	"github.com/Toflex/directory_v2/ent/user"
	"github.com/Toflex/directory_v2/ent/verification"
)

// BusinessQuery is the builder for querying Business entities.
type BusinessQuery struct {
	config
	ctx                      *QueryContext
	order                    []business.OrderOption
	inters                   []Interceptor
	predicates               []predicate.Business
	withSocials              *SocialQuery
	withServices             *BusinessServicesQuery
	withManages              *ManagerQuery
	withRegisteredByUser     *UserQuery
	withVerifications        *VerificationQuery
	withRequestVerifications *RequestVerificationQuery
	withBusinessDocuments    *BusinessDocumentQuery
	withLocations            *BusinessLocationQuery
	withKybMessages          *KYBMessageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BusinessQuery builder.
func (bq *BusinessQuery) Where(ps ...predicate.Business) *BusinessQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BusinessQuery) Limit(limit int) *BusinessQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BusinessQuery) Offset(offset int) *BusinessQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BusinessQuery) Unique(unique bool) *BusinessQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BusinessQuery) Order(o ...business.OrderOption) *BusinessQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QuerySocials chains the current query on the "socials" edge.
func (bq *BusinessQuery) QuerySocials() *SocialQuery {
	query := (&SocialClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, selector),
			sqlgraph.To(social.Table, social.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, business.SocialsTable, business.SocialsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryServices chains the current query on the "services" edge.
func (bq *BusinessQuery) QueryServices() *BusinessServicesQuery {
	query := (&BusinessServicesClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, selector),
			sqlgraph.To(businessservices.Table, businessservices.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, business.ServicesTable, business.ServicesColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryManages chains the current query on the "manages" edge.
func (bq *BusinessQuery) QueryManages() *ManagerQuery {
	query := (&ManagerClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, selector),
			sqlgraph.To(manager.Table, manager.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, business.ManagesTable, business.ManagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRegisteredByUser chains the current query on the "registered_by_user" edge.
func (bq *BusinessQuery) QueryRegisteredByUser() *UserQuery {
	query := (&UserClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, business.RegisteredByUserTable, business.RegisteredByUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVerifications chains the current query on the "verifications" edge.
func (bq *BusinessQuery) QueryVerifications() *VerificationQuery {
	query := (&VerificationClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, selector),
			sqlgraph.To(verification.Table, verification.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, business.VerificationsTable, business.VerificationsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRequestVerifications chains the current query on the "request_verifications" edge.
func (bq *BusinessQuery) QueryRequestVerifications() *RequestVerificationQuery {
	query := (&RequestVerificationClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, selector),
			sqlgraph.To(requestverification.Table, requestverification.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, business.RequestVerificationsTable, business.RequestVerificationsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBusinessDocuments chains the current query on the "business_documents" edge.
func (bq *BusinessQuery) QueryBusinessDocuments() *BusinessDocumentQuery {
	query := (&BusinessDocumentClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, selector),
			sqlgraph.To(businessdocument.Table, businessdocument.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, business.BusinessDocumentsTable, business.BusinessDocumentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocations chains the current query on the "locations" edge.
func (bq *BusinessQuery) QueryLocations() *BusinessLocationQuery {
	query := (&BusinessLocationClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, selector),
			sqlgraph.To(businesslocation.Table, businesslocation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, business.LocationsTable, business.LocationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryKybMessages chains the current query on the "kyb_messages" edge.
func (bq *BusinessQuery) QueryKybMessages() *KYBMessageQuery {
	query := (&KYBMessageClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(business.Table, business.FieldID, selector),
			sqlgraph.To(kybmessage.Table, kybmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, business.KybMessagesTable, business.KybMessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Business entity from the query.
// Returns a *NotFoundError when no Business was found.
func (bq *BusinessQuery) First(ctx context.Context) (*Business, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{business.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BusinessQuery) FirstX(ctx context.Context) *Business {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Business ID from the query.
// Returns a *NotFoundError when no Business ID was found.
func (bq *BusinessQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{business.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BusinessQuery) FirstIDX(ctx context.Context) string {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Business entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Business entity is found.
// Returns a *NotFoundError when no Business entities are found.
func (bq *BusinessQuery) Only(ctx context.Context) (*Business, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{business.Label}
	default:
		return nil, &NotSingularError{business.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BusinessQuery) OnlyX(ctx context.Context) *Business {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Business ID in the query.
// Returns a *NotSingularError when more than one Business ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BusinessQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{business.Label}
	default:
		err = &NotSingularError{business.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BusinessQuery) OnlyIDX(ctx context.Context) string {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Businesses.
func (bq *BusinessQuery) All(ctx context.Context) ([]*Business, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryAll)
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Business, *BusinessQuery]()
	return withInterceptors[[]*Business](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BusinessQuery) AllX(ctx context.Context) []*Business {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Business IDs.
func (bq *BusinessQuery) IDs(ctx context.Context) (ids []string, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryIDs)
	if err = bq.Select(business.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BusinessQuery) IDsX(ctx context.Context) []string {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BusinessQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryCount)
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BusinessQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BusinessQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BusinessQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryExist)
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BusinessQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BusinessQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BusinessQuery) Clone() *BusinessQuery {
	if bq == nil {
		return nil
	}
	return &BusinessQuery{
		config:                   bq.config,
		ctx:                      bq.ctx.Clone(),
		order:                    append([]business.OrderOption{}, bq.order...),
		inters:                   append([]Interceptor{}, bq.inters...),
		predicates:               append([]predicate.Business{}, bq.predicates...),
		withSocials:              bq.withSocials.Clone(),
		withServices:             bq.withServices.Clone(),
		withManages:              bq.withManages.Clone(),
		withRegisteredByUser:     bq.withRegisteredByUser.Clone(),
		withVerifications:        bq.withVerifications.Clone(),
		withRequestVerifications: bq.withRequestVerifications.Clone(),
		withBusinessDocuments:    bq.withBusinessDocuments.Clone(),
		withLocations:            bq.withLocations.Clone(),
		withKybMessages:          bq.withKybMessages.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithSocials tells the query-builder to eager-load the nodes that are connected to
// the "socials" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BusinessQuery) WithSocials(opts ...func(*SocialQuery)) *BusinessQuery {
	query := (&SocialClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withSocials = query
	return bq
}

// WithServices tells the query-builder to eager-load the nodes that are connected to
// the "services" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BusinessQuery) WithServices(opts ...func(*BusinessServicesQuery)) *BusinessQuery {
	query := (&BusinessServicesClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withServices = query
	return bq
}

// WithManages tells the query-builder to eager-load the nodes that are connected to
// the "manages" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BusinessQuery) WithManages(opts ...func(*ManagerQuery)) *BusinessQuery {
	query := (&ManagerClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withManages = query
	return bq
}

// WithRegisteredByUser tells the query-builder to eager-load the nodes that are connected to
// the "registered_by_user" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BusinessQuery) WithRegisteredByUser(opts ...func(*UserQuery)) *BusinessQuery {
	query := (&UserClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withRegisteredByUser = query
	return bq
}

// WithVerifications tells the query-builder to eager-load the nodes that are connected to
// the "verifications" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BusinessQuery) WithVerifications(opts ...func(*VerificationQuery)) *BusinessQuery {
	query := (&VerificationClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withVerifications = query
	return bq
}

// WithRequestVerifications tells the query-builder to eager-load the nodes that are connected to
// the "request_verifications" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BusinessQuery) WithRequestVerifications(opts ...func(*RequestVerificationQuery)) *BusinessQuery {
	query := (&RequestVerificationClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withRequestVerifications = query
	return bq
}

// WithBusinessDocuments tells the query-builder to eager-load the nodes that are connected to
// the "business_documents" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BusinessQuery) WithBusinessDocuments(opts ...func(*BusinessDocumentQuery)) *BusinessQuery {
	query := (&BusinessDocumentClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withBusinessDocuments = query
	return bq
}

// WithLocations tells the query-builder to eager-load the nodes that are connected to
// the "locations" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BusinessQuery) WithLocations(opts ...func(*BusinessLocationQuery)) *BusinessQuery {
	query := (&BusinessLocationClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withLocations = query
	return bq
}

// WithKybMessages tells the query-builder to eager-load the nodes that are connected to
// the "kyb_messages" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BusinessQuery) WithKybMessages(opts ...func(*KYBMessageQuery)) *BusinessQuery {
	query := (&KYBMessageClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withKybMessages = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Business.Query().
//		GroupBy(business.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BusinessQuery) GroupBy(field string, fields ...string) *BusinessGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BusinessGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = business.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Business.Query().
//		Select(business.FieldCreatedAt).
//		Scan(ctx, &v)
func (bq *BusinessQuery) Select(fields ...string) *BusinessSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BusinessSelect{BusinessQuery: bq}
	sbuild.label = business.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BusinessSelect configured with the given aggregations.
func (bq *BusinessQuery) Aggregate(fns ...AggregateFunc) *BusinessSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BusinessQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !business.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BusinessQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Business, error) {
	var (
		nodes       = []*Business{}
		_spec       = bq.querySpec()
		loadedTypes = [9]bool{
			bq.withSocials != nil,
			bq.withServices != nil,
			bq.withManages != nil,
			bq.withRegisteredByUser != nil,
			bq.withVerifications != nil,
			bq.withRequestVerifications != nil,
			bq.withBusinessDocuments != nil,
			bq.withLocations != nil,
			bq.withKybMessages != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Business).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Business{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withSocials; query != nil {
		if err := bq.loadSocials(ctx, query, nodes,
			func(n *Business) { n.Edges.Socials = []*Social{} },
			func(n *Business, e *Social) { n.Edges.Socials = append(n.Edges.Socials, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withServices; query != nil {
		if err := bq.loadServices(ctx, query, nodes,
			func(n *Business) { n.Edges.Services = []*BusinessServices{} },
			func(n *Business, e *BusinessServices) { n.Edges.Services = append(n.Edges.Services, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withManages; query != nil {
		if err := bq.loadManages(ctx, query, nodes,
			func(n *Business) { n.Edges.Manages = []*Manager{} },
			func(n *Business, e *Manager) { n.Edges.Manages = append(n.Edges.Manages, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withRegisteredByUser; query != nil {
		if err := bq.loadRegisteredByUser(ctx, query, nodes, nil,
			func(n *Business, e *User) { n.Edges.RegisteredByUser = e }); err != nil {
			return nil, err
		}
	}
	if query := bq.withVerifications; query != nil {
		if err := bq.loadVerifications(ctx, query, nodes,
			func(n *Business) { n.Edges.Verifications = []*Verification{} },
			func(n *Business, e *Verification) { n.Edges.Verifications = append(n.Edges.Verifications, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withRequestVerifications; query != nil {
		if err := bq.loadRequestVerifications(ctx, query, nodes,
			func(n *Business) { n.Edges.RequestVerifications = []*RequestVerification{} },
			func(n *Business, e *RequestVerification) {
				n.Edges.RequestVerifications = append(n.Edges.RequestVerifications, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := bq.withBusinessDocuments; query != nil {
		if err := bq.loadBusinessDocuments(ctx, query, nodes,
			func(n *Business) { n.Edges.BusinessDocuments = []*BusinessDocument{} },
			func(n *Business, e *BusinessDocument) {
				n.Edges.BusinessDocuments = append(n.Edges.BusinessDocuments, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := bq.withLocations; query != nil {
		if err := bq.loadLocations(ctx, query, nodes,
			func(n *Business) { n.Edges.Locations = []*BusinessLocation{} },
			func(n *Business, e *BusinessLocation) { n.Edges.Locations = append(n.Edges.Locations, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withKybMessages; query != nil {
		if err := bq.loadKybMessages(ctx, query, nodes,
			func(n *Business) { n.Edges.KybMessages = []*KYBMessage{} },
			func(n *Business, e *KYBMessage) { n.Edges.KybMessages = append(n.Edges.KybMessages, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BusinessQuery) loadSocials(ctx context.Context, query *SocialQuery, nodes []*Business, init func(*Business), assign func(*Business, *Social)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Business)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(social.FieldBusinessID)
	}
	query.Where(predicate.Social(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(business.SocialsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BusinessQuery) loadServices(ctx context.Context, query *BusinessServicesQuery, nodes []*Business, init func(*Business), assign func(*Business, *BusinessServices)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Business)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(businessservices.FieldBusinessID)
	}
	query.Where(predicate.BusinessServices(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(business.ServicesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BusinessQuery) loadManages(ctx context.Context, query *ManagerQuery, nodes []*Business, init func(*Business), assign func(*Business, *Manager)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Business)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(manager.FieldBusinessID)
	}
	query.Where(predicate.Manager(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(business.ManagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BusinessQuery) loadRegisteredByUser(ctx context.Context, query *UserQuery, nodes []*Business, init func(*Business), assign func(*Business, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Business)
	for i := range nodes {
		if nodes[i].RegisteredBy == nil {
			continue
		}
		fk := *nodes[i].RegisteredBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "registered_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bq *BusinessQuery) loadVerifications(ctx context.Context, query *VerificationQuery, nodes []*Business, init func(*Business), assign func(*Business, *Verification)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[string]*Business)
	nids := make(map[string]map[*Business]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(business.VerificationsTable)
		s.Join(joinT).On(s.C(verification.FieldID), joinT.C(business.VerificationsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(business.VerificationsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(business.VerificationsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*Business]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Verification](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "verifications" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (bq *BusinessQuery) loadRequestVerifications(ctx context.Context, query *RequestVerificationQuery, nodes []*Business, init func(*Business), assign func(*Business, *RequestVerification)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[string]*Business)
	nids := make(map[string]map[*Business]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(business.RequestVerificationsTable)
		s.Join(joinT).On(s.C(requestverification.FieldID), joinT.C(business.RequestVerificationsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(business.RequestVerificationsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(business.RequestVerificationsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*Business]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*RequestVerification](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "request_verifications" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (bq *BusinessQuery) loadBusinessDocuments(ctx context.Context, query *BusinessDocumentQuery, nodes []*Business, init func(*Business), assign func(*Business, *BusinessDocument)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Business)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.BusinessDocument(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(business.BusinessDocumentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.business_business_documents
		if fk == nil {
			return fmt.Errorf(`foreign-key "business_business_documents" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_business_documents" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BusinessQuery) loadLocations(ctx context.Context, query *BusinessLocationQuery, nodes []*Business, init func(*Business), assign func(*Business, *BusinessLocation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Business)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.BusinessLocation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(business.LocationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.business_locations
		if fk == nil {
			return fmt.Errorf(`foreign-key "business_locations" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_locations" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BusinessQuery) loadKybMessages(ctx context.Context, query *KYBMessageQuery, nodes []*Business, init func(*Business), assign func(*Business, *KYBMessage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Business)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.KYBMessage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(business.KybMessagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.business_kyb_messages
		if fk == nil {
			return fmt.Errorf(`foreign-key "business_kyb_messages" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_kyb_messages" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bq *BusinessQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BusinessQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(business.Table, business.Columns, sqlgraph.NewFieldSpec(business.FieldID, field.TypeString))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, business.FieldID)
		for i := range fields {
			if fields[i] != business.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if bq.withRegisteredByUser != nil {
			_spec.Node.AddColumnOnce(business.FieldRegisteredBy)
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BusinessQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(business.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = business.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BusinessGroupBy is the group-by builder for Business entities.
type BusinessGroupBy struct {
	selector
	build *BusinessQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BusinessGroupBy) Aggregate(fns ...AggregateFunc) *BusinessGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BusinessGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, ent.OpQueryGroupBy)
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BusinessQuery, *BusinessGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BusinessGroupBy) sqlScan(ctx context.Context, root *BusinessQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BusinessSelect is the builder for selecting fields of Business entities.
type BusinessSelect struct {
	*BusinessQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BusinessSelect) Aggregate(fns ...AggregateFunc) *BusinessSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BusinessSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, ent.OpQuerySelect)
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BusinessQuery, *BusinessSelect](ctx, bs.BusinessQuery, bs, bs.inters, v)
}

func (bs *BusinessSelect) sqlScan(ctx context.Context, root *BusinessQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
