// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Toflex/directory_v2/ent/business"
	"github.com/Toflex/directory_v2/ent/businessdocument"
	"github.com/Toflex/directory_v2/ent/kybdocument"
	"github.com/Toflex/directory_v2/ent/predicate"
)

// BusinessDocumentQuery is the builder for querying BusinessDocument entities.
type BusinessDocumentQuery struct {
	config
	ctx             *QueryContext
	order           []businessdocument.OrderOption
	inters          []Interceptor
	predicates      []predicate.BusinessDocument
	withBusiness    *BusinessQuery
	withKybDocument *KYBDocumentQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BusinessDocumentQuery builder.
func (bdq *BusinessDocumentQuery) Where(ps ...predicate.BusinessDocument) *BusinessDocumentQuery {
	bdq.predicates = append(bdq.predicates, ps...)
	return bdq
}

// Limit the number of records to be returned by this query.
func (bdq *BusinessDocumentQuery) Limit(limit int) *BusinessDocumentQuery {
	bdq.ctx.Limit = &limit
	return bdq
}

// Offset to start from.
func (bdq *BusinessDocumentQuery) Offset(offset int) *BusinessDocumentQuery {
	bdq.ctx.Offset = &offset
	return bdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bdq *BusinessDocumentQuery) Unique(unique bool) *BusinessDocumentQuery {
	bdq.ctx.Unique = &unique
	return bdq
}

// Order specifies how the records should be ordered.
func (bdq *BusinessDocumentQuery) Order(o ...businessdocument.OrderOption) *BusinessDocumentQuery {
	bdq.order = append(bdq.order, o...)
	return bdq
}

// QueryBusiness chains the current query on the "business" edge.
func (bdq *BusinessDocumentQuery) QueryBusiness() *BusinessQuery {
	query := (&BusinessClient{config: bdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(businessdocument.Table, businessdocument.FieldID, selector),
			sqlgraph.To(business.Table, business.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, businessdocument.BusinessTable, businessdocument.BusinessColumn),
		)
		fromU = sqlgraph.SetNeighbors(bdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryKybDocument chains the current query on the "kyb_document" edge.
func (bdq *BusinessDocumentQuery) QueryKybDocument() *KYBDocumentQuery {
	query := (&KYBDocumentClient{config: bdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(businessdocument.Table, businessdocument.FieldID, selector),
			sqlgraph.To(kybdocument.Table, kybdocument.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, businessdocument.KybDocumentTable, businessdocument.KybDocumentPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(bdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BusinessDocument entity from the query.
// Returns a *NotFoundError when no BusinessDocument was found.
func (bdq *BusinessDocumentQuery) First(ctx context.Context) (*BusinessDocument, error) {
	nodes, err := bdq.Limit(1).All(setContextOp(ctx, bdq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{businessdocument.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bdq *BusinessDocumentQuery) FirstX(ctx context.Context) *BusinessDocument {
	node, err := bdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BusinessDocument ID from the query.
// Returns a *NotFoundError when no BusinessDocument ID was found.
func (bdq *BusinessDocumentQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = bdq.Limit(1).IDs(setContextOp(ctx, bdq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{businessdocument.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bdq *BusinessDocumentQuery) FirstIDX(ctx context.Context) string {
	id, err := bdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BusinessDocument entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BusinessDocument entity is found.
// Returns a *NotFoundError when no BusinessDocument entities are found.
func (bdq *BusinessDocumentQuery) Only(ctx context.Context) (*BusinessDocument, error) {
	nodes, err := bdq.Limit(2).All(setContextOp(ctx, bdq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{businessdocument.Label}
	default:
		return nil, &NotSingularError{businessdocument.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bdq *BusinessDocumentQuery) OnlyX(ctx context.Context) *BusinessDocument {
	node, err := bdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BusinessDocument ID in the query.
// Returns a *NotSingularError when more than one BusinessDocument ID is found.
// Returns a *NotFoundError when no entities are found.
func (bdq *BusinessDocumentQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = bdq.Limit(2).IDs(setContextOp(ctx, bdq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{businessdocument.Label}
	default:
		err = &NotSingularError{businessdocument.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bdq *BusinessDocumentQuery) OnlyIDX(ctx context.Context) string {
	id, err := bdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BusinessDocuments.
func (bdq *BusinessDocumentQuery) All(ctx context.Context) ([]*BusinessDocument, error) {
	ctx = setContextOp(ctx, bdq.ctx, ent.OpQueryAll)
	if err := bdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BusinessDocument, *BusinessDocumentQuery]()
	return withInterceptors[[]*BusinessDocument](ctx, bdq, qr, bdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bdq *BusinessDocumentQuery) AllX(ctx context.Context) []*BusinessDocument {
	nodes, err := bdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BusinessDocument IDs.
func (bdq *BusinessDocumentQuery) IDs(ctx context.Context) (ids []string, err error) {
	if bdq.ctx.Unique == nil && bdq.path != nil {
		bdq.Unique(true)
	}
	ctx = setContextOp(ctx, bdq.ctx, ent.OpQueryIDs)
	if err = bdq.Select(businessdocument.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bdq *BusinessDocumentQuery) IDsX(ctx context.Context) []string {
	ids, err := bdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bdq *BusinessDocumentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bdq.ctx, ent.OpQueryCount)
	if err := bdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bdq, querierCount[*BusinessDocumentQuery](), bdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bdq *BusinessDocumentQuery) CountX(ctx context.Context) int {
	count, err := bdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bdq *BusinessDocumentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bdq.ctx, ent.OpQueryExist)
	switch _, err := bdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bdq *BusinessDocumentQuery) ExistX(ctx context.Context) bool {
	exist, err := bdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BusinessDocumentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bdq *BusinessDocumentQuery) Clone() *BusinessDocumentQuery {
	if bdq == nil {
		return nil
	}
	return &BusinessDocumentQuery{
		config:          bdq.config,
		ctx:             bdq.ctx.Clone(),
		order:           append([]businessdocument.OrderOption{}, bdq.order...),
		inters:          append([]Interceptor{}, bdq.inters...),
		predicates:      append([]predicate.BusinessDocument{}, bdq.predicates...),
		withBusiness:    bdq.withBusiness.Clone(),
		withKybDocument: bdq.withKybDocument.Clone(),
		// clone intermediate query.
		sql:  bdq.sql.Clone(),
		path: bdq.path,
	}
}

// WithBusiness tells the query-builder to eager-load the nodes that are connected to
// the "business" edge. The optional arguments are used to configure the query builder of the edge.
func (bdq *BusinessDocumentQuery) WithBusiness(opts ...func(*BusinessQuery)) *BusinessDocumentQuery {
	query := (&BusinessClient{config: bdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bdq.withBusiness = query
	return bdq
}

// WithKybDocument tells the query-builder to eager-load the nodes that are connected to
// the "kyb_document" edge. The optional arguments are used to configure the query builder of the edge.
func (bdq *BusinessDocumentQuery) WithKybDocument(opts ...func(*KYBDocumentQuery)) *BusinessDocumentQuery {
	query := (&KYBDocumentClient{config: bdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bdq.withKybDocument = query
	return bdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BusinessDocument.Query().
//		GroupBy(businessdocument.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bdq *BusinessDocumentQuery) GroupBy(field string, fields ...string) *BusinessDocumentGroupBy {
	bdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BusinessDocumentGroupBy{build: bdq}
	grbuild.flds = &bdq.ctx.Fields
	grbuild.label = businessdocument.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.BusinessDocument.Query().
//		Select(businessdocument.FieldCreatedAt).
//		Scan(ctx, &v)
func (bdq *BusinessDocumentQuery) Select(fields ...string) *BusinessDocumentSelect {
	bdq.ctx.Fields = append(bdq.ctx.Fields, fields...)
	sbuild := &BusinessDocumentSelect{BusinessDocumentQuery: bdq}
	sbuild.label = businessdocument.Label
	sbuild.flds, sbuild.scan = &bdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BusinessDocumentSelect configured with the given aggregations.
func (bdq *BusinessDocumentQuery) Aggregate(fns ...AggregateFunc) *BusinessDocumentSelect {
	return bdq.Select().Aggregate(fns...)
}

func (bdq *BusinessDocumentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bdq); err != nil {
				return err
			}
		}
	}
	for _, f := range bdq.ctx.Fields {
		if !businessdocument.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bdq.path != nil {
		prev, err := bdq.path(ctx)
		if err != nil {
			return err
		}
		bdq.sql = prev
	}
	return nil
}

func (bdq *BusinessDocumentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BusinessDocument, error) {
	var (
		nodes       = []*BusinessDocument{}
		withFKs     = bdq.withFKs
		_spec       = bdq.querySpec()
		loadedTypes = [2]bool{
			bdq.withBusiness != nil,
			bdq.withKybDocument != nil,
		}
	)
	if bdq.withBusiness != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, businessdocument.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BusinessDocument).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BusinessDocument{config: bdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bdq.withBusiness; query != nil {
		if err := bdq.loadBusiness(ctx, query, nodes, nil,
			func(n *BusinessDocument, e *Business) { n.Edges.Business = e }); err != nil {
			return nil, err
		}
	}
	if query := bdq.withKybDocument; query != nil {
		if err := bdq.loadKybDocument(ctx, query, nodes,
			func(n *BusinessDocument) { n.Edges.KybDocument = []*KYBDocument{} },
			func(n *BusinessDocument, e *KYBDocument) { n.Edges.KybDocument = append(n.Edges.KybDocument, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bdq *BusinessDocumentQuery) loadBusiness(ctx context.Context, query *BusinessQuery, nodes []*BusinessDocument, init func(*BusinessDocument), assign func(*BusinessDocument, *Business)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*BusinessDocument)
	for i := range nodes {
		if nodes[i].business_business_documents == nil {
			continue
		}
		fk := *nodes[i].business_business_documents
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(business.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "business_business_documents" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bdq *BusinessDocumentQuery) loadKybDocument(ctx context.Context, query *KYBDocumentQuery, nodes []*BusinessDocument, init func(*BusinessDocument), assign func(*BusinessDocument, *KYBDocument)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[string]*BusinessDocument)
	nids := make(map[string]map[*BusinessDocument]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(businessdocument.KybDocumentTable)
		s.Join(joinT).On(s.C(kybdocument.FieldID), joinT.C(businessdocument.KybDocumentPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(businessdocument.KybDocumentPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(businessdocument.KybDocumentPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*BusinessDocument]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*KYBDocument](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "kyb_document" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (bdq *BusinessDocumentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bdq.querySpec()
	_spec.Node.Columns = bdq.ctx.Fields
	if len(bdq.ctx.Fields) > 0 {
		_spec.Unique = bdq.ctx.Unique != nil && *bdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bdq.driver, _spec)
}

func (bdq *BusinessDocumentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(businessdocument.Table, businessdocument.Columns, sqlgraph.NewFieldSpec(businessdocument.FieldID, field.TypeString))
	_spec.From = bdq.sql
	if unique := bdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bdq.path != nil {
		_spec.Unique = true
	}
	if fields := bdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, businessdocument.FieldID)
		for i := range fields {
			if fields[i] != businessdocument.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bdq *BusinessDocumentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bdq.driver.Dialect())
	t1 := builder.Table(businessdocument.Table)
	columns := bdq.ctx.Fields
	if len(columns) == 0 {
		columns = businessdocument.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bdq.sql != nil {
		selector = bdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bdq.ctx.Unique != nil && *bdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bdq.predicates {
		p(selector)
	}
	for _, p := range bdq.order {
		p(selector)
	}
	if offset := bdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BusinessDocumentGroupBy is the group-by builder for BusinessDocument entities.
type BusinessDocumentGroupBy struct {
	selector
	build *BusinessDocumentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bdgb *BusinessDocumentGroupBy) Aggregate(fns ...AggregateFunc) *BusinessDocumentGroupBy {
	bdgb.fns = append(bdgb.fns, fns...)
	return bdgb
}

// Scan applies the selector query and scans the result into the given value.
func (bdgb *BusinessDocumentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bdgb.build.ctx, ent.OpQueryGroupBy)
	if err := bdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BusinessDocumentQuery, *BusinessDocumentGroupBy](ctx, bdgb.build, bdgb, bdgb.build.inters, v)
}

func (bdgb *BusinessDocumentGroupBy) sqlScan(ctx context.Context, root *BusinessDocumentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bdgb.fns))
	for _, fn := range bdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bdgb.flds)+len(bdgb.fns))
		for _, f := range *bdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BusinessDocumentSelect is the builder for selecting fields of BusinessDocument entities.
type BusinessDocumentSelect struct {
	*BusinessDocumentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bds *BusinessDocumentSelect) Aggregate(fns ...AggregateFunc) *BusinessDocumentSelect {
	bds.fns = append(bds.fns, fns...)
	return bds
}

// Scan applies the selector query and scans the result into the given value.
func (bds *BusinessDocumentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bds.ctx, ent.OpQuerySelect)
	if err := bds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BusinessDocumentQuery, *BusinessDocumentSelect](ctx, bds.BusinessDocumentQuery, bds, bds.inters, v)
}

func (bds *BusinessDocumentSelect) sqlScan(ctx context.Context, root *BusinessDocumentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bds.fns))
	for _, fn := range bds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
