// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Toflex/directory_v2/ent/business"
	"github.com/Toflex/directory_v2/ent/manager"
	"github.com/Toflex/directory_v2/ent/social"
)

// BusinessCreate is the builder for creating a Business entity.
type BusinessCreate struct {
	config
	mutation *BusinessMutation
	hooks    []Hook
}

// SetCategory sets the "category" field.
func (bc *BusinessCreate) SetCategory(s string) *BusinessCreate {
	bc.mutation.SetCategory(s)
	return bc
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (bc *BusinessCreate) SetNillableCategory(s *string) *BusinessCreate {
	if s != nil {
		bc.SetCategory(*s)
	}
	return bc
}

// SetName sets the "name" field.
func (bc *BusinessCreate) SetName(s string) *BusinessCreate {
	bc.mutation.SetName(s)
	return bc
}

// SetLogoURL sets the "logo_url" field.
func (bc *BusinessCreate) SetLogoURL(s string) *BusinessCreate {
	bc.mutation.SetLogoURL(s)
	return bc
}

// SetEmail sets the "email" field.
func (bc *BusinessCreate) SetEmail(s string) *BusinessCreate {
	bc.mutation.SetEmail(s)
	return bc
}

// SetWebsite sets the "website" field.
func (bc *BusinessCreate) SetWebsite(s string) *BusinessCreate {
	bc.mutation.SetWebsite(s)
	return bc
}

// SetDisabled sets the "disabled" field.
func (bc *BusinessCreate) SetDisabled(b bool) *BusinessCreate {
	bc.mutation.SetDisabled(b)
	return bc
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (bc *BusinessCreate) SetNillableDisabled(b *bool) *BusinessCreate {
	if b != nil {
		bc.SetDisabled(*b)
	}
	return bc
}

// SetDisabledAt sets the "disabled_at" field.
func (bc *BusinessCreate) SetDisabledAt(t time.Time) *BusinessCreate {
	bc.mutation.SetDisabledAt(t)
	return bc
}

// SetNillableDisabledAt sets the "disabled_at" field if the given value is not nil.
func (bc *BusinessCreate) SetNillableDisabledAt(t *time.Time) *BusinessCreate {
	if t != nil {
		bc.SetDisabledAt(*t)
	}
	return bc
}

// SetDisableReason sets the "disable_reason" field.
func (bc *BusinessCreate) SetDisableReason(s string) *BusinessCreate {
	bc.mutation.SetDisableReason(s)
	return bc
}

// SetVerified sets the "verified" field.
func (bc *BusinessCreate) SetVerified(b bool) *BusinessCreate {
	bc.mutation.SetVerified(b)
	return bc
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (bc *BusinessCreate) SetNillableVerified(b *bool) *BusinessCreate {
	if b != nil {
		bc.SetVerified(*b)
	}
	return bc
}

// SetVerifiedAt sets the "verified_at" field.
func (bc *BusinessCreate) SetVerifiedAt(t time.Time) *BusinessCreate {
	bc.mutation.SetVerifiedAt(t)
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BusinessCreate) SetCreatedAt(t time.Time) *BusinessCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BusinessCreate) SetNillableCreatedAt(t *time.Time) *BusinessCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// AddBusinessSocialIDs adds the "business_social" edge to the Social entity by IDs.
func (bc *BusinessCreate) AddBusinessSocialIDs(ids ...int) *BusinessCreate {
	bc.mutation.AddBusinessSocialIDs(ids...)
	return bc
}

// AddBusinessSocial adds the "business_social" edges to the Social entity.
func (bc *BusinessCreate) AddBusinessSocial(s ...*Social) *BusinessCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return bc.AddBusinessSocialIDs(ids...)
}

// AddBusinessManagerIDs adds the "business_manager" edge to the Manager entity by IDs.
func (bc *BusinessCreate) AddBusinessManagerIDs(ids ...int) *BusinessCreate {
	bc.mutation.AddBusinessManagerIDs(ids...)
	return bc
}

// AddBusinessManager adds the "business_manager" edges to the Manager entity.
func (bc *BusinessCreate) AddBusinessManager(m ...*Manager) *BusinessCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return bc.AddBusinessManagerIDs(ids...)
}

// Mutation returns the BusinessMutation object of the builder.
func (bc *BusinessCreate) Mutation() *BusinessMutation {
	return bc.mutation
}

// Save creates the Business in the database.
func (bc *BusinessCreate) Save(ctx context.Context) (*Business, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BusinessCreate) SaveX(ctx context.Context) *Business {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BusinessCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BusinessCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BusinessCreate) defaults() {
	if _, ok := bc.mutation.Category(); !ok {
		v := business.DefaultCategory
		bc.mutation.SetCategory(v)
	}
	if _, ok := bc.mutation.Disabled(); !ok {
		v := business.DefaultDisabled
		bc.mutation.SetDisabled(v)
	}
	if _, ok := bc.mutation.DisabledAt(); !ok {
		v := business.DefaultDisabledAt()
		bc.mutation.SetDisabledAt(v)
	}
	if _, ok := bc.mutation.Verified(); !ok {
		v := business.DefaultVerified
		bc.mutation.SetVerified(v)
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := business.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BusinessCreate) check() error {
	if _, ok := bc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Business.category"`)}
	}
	if _, ok := bc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Business.name"`)}
	}
	if v, ok := bc.mutation.Name(); ok {
		if err := business.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Business.name": %w`, err)}
		}
	}
	if _, ok := bc.mutation.LogoURL(); !ok {
		return &ValidationError{Name: "logo_url", err: errors.New(`ent: missing required field "Business.logo_url"`)}
	}
	if _, ok := bc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Business.email"`)}
	}
	if v, ok := bc.mutation.Email(); ok {
		if err := business.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Business.email": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Website(); !ok {
		return &ValidationError{Name: "website", err: errors.New(`ent: missing required field "Business.website"`)}
	}
	if _, ok := bc.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "Business.disabled"`)}
	}
	if _, ok := bc.mutation.DisabledAt(); !ok {
		return &ValidationError{Name: "disabled_at", err: errors.New(`ent: missing required field "Business.disabled_at"`)}
	}
	if _, ok := bc.mutation.DisableReason(); !ok {
		return &ValidationError{Name: "disable_reason", err: errors.New(`ent: missing required field "Business.disable_reason"`)}
	}
	if _, ok := bc.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "Business.verified"`)}
	}
	if _, ok := bc.mutation.VerifiedAt(); !ok {
		return &ValidationError{Name: "verified_at", err: errors.New(`ent: missing required field "Business.verified_at"`)}
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Business.created_at"`)}
	}
	return nil
}

func (bc *BusinessCreate) sqlSave(ctx context.Context) (*Business, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BusinessCreate) createSpec() (*Business, *sqlgraph.CreateSpec) {
	var (
		_node = &Business{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(business.Table, sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt))
	)
	if value, ok := bc.mutation.Category(); ok {
		_spec.SetField(business.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := bc.mutation.Name(); ok {
		_spec.SetField(business.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := bc.mutation.LogoURL(); ok {
		_spec.SetField(business.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = &value
	}
	if value, ok := bc.mutation.Email(); ok {
		_spec.SetField(business.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := bc.mutation.Website(); ok {
		_spec.SetField(business.FieldWebsite, field.TypeString, value)
		_node.Website = &value
	}
	if value, ok := bc.mutation.Disabled(); ok {
		_spec.SetField(business.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := bc.mutation.DisabledAt(); ok {
		_spec.SetField(business.FieldDisabledAt, field.TypeTime, value)
		_node.DisabledAt = value
	}
	if value, ok := bc.mutation.DisableReason(); ok {
		_spec.SetField(business.FieldDisableReason, field.TypeString, value)
		_node.DisableReason = &value
	}
	if value, ok := bc.mutation.Verified(); ok {
		_spec.SetField(business.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := bc.mutation.VerifiedAt(); ok {
		_spec.SetField(business.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(business.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := bc.mutation.BusinessSocialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   business.BusinessSocialTable,
			Columns: []string{business.BusinessSocialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(social.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.BusinessManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   business.BusinessManagerTable,
			Columns: []string{business.BusinessManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(manager.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BusinessCreateBulk is the builder for creating many Business entities in bulk.
type BusinessCreateBulk struct {
	config
	err      error
	builders []*BusinessCreate
}

// Save creates the Business entities in the database.
func (bcb *BusinessCreateBulk) Save(ctx context.Context) ([]*Business, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Business, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BusinessMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BusinessCreateBulk) SaveX(ctx context.Context) []*Business {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BusinessCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BusinessCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
