// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Toflex/directory_v2/ent/nubandynamicaccount"
	"github.com/Toflex/directory_v2/ent/predicate"
	"github.com/Toflex/directory_v2/ent/wallet"
)

// NubanDynamicAccountQuery is the builder for querying NubanDynamicAccount entities.
type NubanDynamicAccountQuery struct {
	config
	ctx        *QueryContext
	order      []nubandynamicaccount.OrderOption
	inters     []Interceptor
	predicates []predicate.NubanDynamicAccount
	withWallet *WalletQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NubanDynamicAccountQuery builder.
func (ndaq *NubanDynamicAccountQuery) Where(ps ...predicate.NubanDynamicAccount) *NubanDynamicAccountQuery {
	ndaq.predicates = append(ndaq.predicates, ps...)
	return ndaq
}

// Limit the number of records to be returned by this query.
func (ndaq *NubanDynamicAccountQuery) Limit(limit int) *NubanDynamicAccountQuery {
	ndaq.ctx.Limit = &limit
	return ndaq
}

// Offset to start from.
func (ndaq *NubanDynamicAccountQuery) Offset(offset int) *NubanDynamicAccountQuery {
	ndaq.ctx.Offset = &offset
	return ndaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ndaq *NubanDynamicAccountQuery) Unique(unique bool) *NubanDynamicAccountQuery {
	ndaq.ctx.Unique = &unique
	return ndaq
}

// Order specifies how the records should be ordered.
func (ndaq *NubanDynamicAccountQuery) Order(o ...nubandynamicaccount.OrderOption) *NubanDynamicAccountQuery {
	ndaq.order = append(ndaq.order, o...)
	return ndaq
}

// QueryWallet chains the current query on the "wallet" edge.
func (ndaq *NubanDynamicAccountQuery) QueryWallet() *WalletQuery {
	query := (&WalletClient{config: ndaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ndaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ndaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nubandynamicaccount.Table, nubandynamicaccount.FieldID, selector),
			sqlgraph.To(wallet.Table, wallet.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nubandynamicaccount.WalletTable, nubandynamicaccount.WalletColumn),
		)
		fromU = sqlgraph.SetNeighbors(ndaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NubanDynamicAccount entity from the query.
// Returns a *NotFoundError when no NubanDynamicAccount was found.
func (ndaq *NubanDynamicAccountQuery) First(ctx context.Context) (*NubanDynamicAccount, error) {
	nodes, err := ndaq.Limit(1).All(setContextOp(ctx, ndaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nubandynamicaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ndaq *NubanDynamicAccountQuery) FirstX(ctx context.Context) *NubanDynamicAccount {
	node, err := ndaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NubanDynamicAccount ID from the query.
// Returns a *NotFoundError when no NubanDynamicAccount ID was found.
func (ndaq *NubanDynamicAccountQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ndaq.Limit(1).IDs(setContextOp(ctx, ndaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nubandynamicaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ndaq *NubanDynamicAccountQuery) FirstIDX(ctx context.Context) string {
	id, err := ndaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NubanDynamicAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NubanDynamicAccount entity is found.
// Returns a *NotFoundError when no NubanDynamicAccount entities are found.
func (ndaq *NubanDynamicAccountQuery) Only(ctx context.Context) (*NubanDynamicAccount, error) {
	nodes, err := ndaq.Limit(2).All(setContextOp(ctx, ndaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nubandynamicaccount.Label}
	default:
		return nil, &NotSingularError{nubandynamicaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ndaq *NubanDynamicAccountQuery) OnlyX(ctx context.Context) *NubanDynamicAccount {
	node, err := ndaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NubanDynamicAccount ID in the query.
// Returns a *NotSingularError when more than one NubanDynamicAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (ndaq *NubanDynamicAccountQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ndaq.Limit(2).IDs(setContextOp(ctx, ndaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nubandynamicaccount.Label}
	default:
		err = &NotSingularError{nubandynamicaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ndaq *NubanDynamicAccountQuery) OnlyIDX(ctx context.Context) string {
	id, err := ndaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NubanDynamicAccounts.
func (ndaq *NubanDynamicAccountQuery) All(ctx context.Context) ([]*NubanDynamicAccount, error) {
	ctx = setContextOp(ctx, ndaq.ctx, ent.OpQueryAll)
	if err := ndaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NubanDynamicAccount, *NubanDynamicAccountQuery]()
	return withInterceptors[[]*NubanDynamicAccount](ctx, ndaq, qr, ndaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ndaq *NubanDynamicAccountQuery) AllX(ctx context.Context) []*NubanDynamicAccount {
	nodes, err := ndaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NubanDynamicAccount IDs.
func (ndaq *NubanDynamicAccountQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ndaq.ctx.Unique == nil && ndaq.path != nil {
		ndaq.Unique(true)
	}
	ctx = setContextOp(ctx, ndaq.ctx, ent.OpQueryIDs)
	if err = ndaq.Select(nubandynamicaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ndaq *NubanDynamicAccountQuery) IDsX(ctx context.Context) []string {
	ids, err := ndaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ndaq *NubanDynamicAccountQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ndaq.ctx, ent.OpQueryCount)
	if err := ndaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ndaq, querierCount[*NubanDynamicAccountQuery](), ndaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ndaq *NubanDynamicAccountQuery) CountX(ctx context.Context) int {
	count, err := ndaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ndaq *NubanDynamicAccountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ndaq.ctx, ent.OpQueryExist)
	switch _, err := ndaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ndaq *NubanDynamicAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := ndaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NubanDynamicAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ndaq *NubanDynamicAccountQuery) Clone() *NubanDynamicAccountQuery {
	if ndaq == nil {
		return nil
	}
	return &NubanDynamicAccountQuery{
		config:     ndaq.config,
		ctx:        ndaq.ctx.Clone(),
		order:      append([]nubandynamicaccount.OrderOption{}, ndaq.order...),
		inters:     append([]Interceptor{}, ndaq.inters...),
		predicates: append([]predicate.NubanDynamicAccount{}, ndaq.predicates...),
		withWallet: ndaq.withWallet.Clone(),
		// clone intermediate query.
		sql:  ndaq.sql.Clone(),
		path: ndaq.path,
	}
}

// WithWallet tells the query-builder to eager-load the nodes that are connected to
// the "wallet" edge. The optional arguments are used to configure the query builder of the edge.
func (ndaq *NubanDynamicAccountQuery) WithWallet(opts ...func(*WalletQuery)) *NubanDynamicAccountQuery {
	query := (&WalletClient{config: ndaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ndaq.withWallet = query
	return ndaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NubanDynamicAccount.Query().
//		GroupBy(nubandynamicaccount.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ndaq *NubanDynamicAccountQuery) GroupBy(field string, fields ...string) *NubanDynamicAccountGroupBy {
	ndaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NubanDynamicAccountGroupBy{build: ndaq}
	grbuild.flds = &ndaq.ctx.Fields
	grbuild.label = nubandynamicaccount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.NubanDynamicAccount.Query().
//		Select(nubandynamicaccount.FieldCreatedAt).
//		Scan(ctx, &v)
func (ndaq *NubanDynamicAccountQuery) Select(fields ...string) *NubanDynamicAccountSelect {
	ndaq.ctx.Fields = append(ndaq.ctx.Fields, fields...)
	sbuild := &NubanDynamicAccountSelect{NubanDynamicAccountQuery: ndaq}
	sbuild.label = nubandynamicaccount.Label
	sbuild.flds, sbuild.scan = &ndaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NubanDynamicAccountSelect configured with the given aggregations.
func (ndaq *NubanDynamicAccountQuery) Aggregate(fns ...AggregateFunc) *NubanDynamicAccountSelect {
	return ndaq.Select().Aggregate(fns...)
}

func (ndaq *NubanDynamicAccountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ndaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ndaq); err != nil {
				return err
			}
		}
	}
	for _, f := range ndaq.ctx.Fields {
		if !nubandynamicaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ndaq.path != nil {
		prev, err := ndaq.path(ctx)
		if err != nil {
			return err
		}
		ndaq.sql = prev
	}
	return nil
}

func (ndaq *NubanDynamicAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NubanDynamicAccount, error) {
	var (
		nodes       = []*NubanDynamicAccount{}
		withFKs     = ndaq.withFKs
		_spec       = ndaq.querySpec()
		loadedTypes = [1]bool{
			ndaq.withWallet != nil,
		}
	)
	if ndaq.withWallet != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, nubandynamicaccount.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NubanDynamicAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NubanDynamicAccount{config: ndaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ndaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ndaq.withWallet; query != nil {
		if err := ndaq.loadWallet(ctx, query, nodes, nil,
			func(n *NubanDynamicAccount, e *Wallet) { n.Edges.Wallet = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ndaq *NubanDynamicAccountQuery) loadWallet(ctx context.Context, query *WalletQuery, nodes []*NubanDynamicAccount, init func(*NubanDynamicAccount), assign func(*NubanDynamicAccount, *Wallet)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*NubanDynamicAccount)
	for i := range nodes {
		if nodes[i].wallet_nuban_dynamic_account == nil {
			continue
		}
		fk := *nodes[i].wallet_nuban_dynamic_account
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(wallet.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "wallet_nuban_dynamic_account" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ndaq *NubanDynamicAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ndaq.querySpec()
	_spec.Node.Columns = ndaq.ctx.Fields
	if len(ndaq.ctx.Fields) > 0 {
		_spec.Unique = ndaq.ctx.Unique != nil && *ndaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ndaq.driver, _spec)
}

func (ndaq *NubanDynamicAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nubandynamicaccount.Table, nubandynamicaccount.Columns, sqlgraph.NewFieldSpec(nubandynamicaccount.FieldID, field.TypeString))
	_spec.From = ndaq.sql
	if unique := ndaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ndaq.path != nil {
		_spec.Unique = true
	}
	if fields := ndaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nubandynamicaccount.FieldID)
		for i := range fields {
			if fields[i] != nubandynamicaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ndaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ndaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ndaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ndaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ndaq *NubanDynamicAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ndaq.driver.Dialect())
	t1 := builder.Table(nubandynamicaccount.Table)
	columns := ndaq.ctx.Fields
	if len(columns) == 0 {
		columns = nubandynamicaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ndaq.sql != nil {
		selector = ndaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ndaq.ctx.Unique != nil && *ndaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ndaq.predicates {
		p(selector)
	}
	for _, p := range ndaq.order {
		p(selector)
	}
	if offset := ndaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ndaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NubanDynamicAccountGroupBy is the group-by builder for NubanDynamicAccount entities.
type NubanDynamicAccountGroupBy struct {
	selector
	build *NubanDynamicAccountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ndagb *NubanDynamicAccountGroupBy) Aggregate(fns ...AggregateFunc) *NubanDynamicAccountGroupBy {
	ndagb.fns = append(ndagb.fns, fns...)
	return ndagb
}

// Scan applies the selector query and scans the result into the given value.
func (ndagb *NubanDynamicAccountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ndagb.build.ctx, ent.OpQueryGroupBy)
	if err := ndagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NubanDynamicAccountQuery, *NubanDynamicAccountGroupBy](ctx, ndagb.build, ndagb, ndagb.build.inters, v)
}

func (ndagb *NubanDynamicAccountGroupBy) sqlScan(ctx context.Context, root *NubanDynamicAccountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ndagb.fns))
	for _, fn := range ndagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ndagb.flds)+len(ndagb.fns))
		for _, f := range *ndagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ndagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ndagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NubanDynamicAccountSelect is the builder for selecting fields of NubanDynamicAccount entities.
type NubanDynamicAccountSelect struct {
	*NubanDynamicAccountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ndas *NubanDynamicAccountSelect) Aggregate(fns ...AggregateFunc) *NubanDynamicAccountSelect {
	ndas.fns = append(ndas.fns, fns...)
	return ndas
}

// Scan applies the selector query and scans the result into the given value.
func (ndas *NubanDynamicAccountSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ndas.ctx, ent.OpQuerySelect)
	if err := ndas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NubanDynamicAccountQuery, *NubanDynamicAccountSelect](ctx, ndas.NubanDynamicAccountQuery, ndas, ndas.inters, v)
}

func (ndas *NubanDynamicAccountSelect) sqlScan(ctx context.Context, root *NubanDynamicAccountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ndas.fns))
	for _, fn := range ndas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ndas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ndas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
