// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Toflex/directory_v2/ent/business"
	"github.com/Toflex/directory_v2/ent/requestverification"
	"github.com/Toflex/directory_v2/ent/user"
)

// RequestVerificationCreate is the builder for creating a RequestVerification entity.
type RequestVerificationCreate struct {
	config
	mutation *RequestVerificationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (rvc *RequestVerificationCreate) SetCreatedAt(t time.Time) *RequestVerificationCreate {
	rvc.mutation.SetCreatedAt(t)
	return rvc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rvc *RequestVerificationCreate) SetNillableCreatedAt(t *time.Time) *RequestVerificationCreate {
	if t != nil {
		rvc.SetCreatedAt(*t)
	}
	return rvc
}

// SetUpdatedAt sets the "updated_at" field.
func (rvc *RequestVerificationCreate) SetUpdatedAt(t time.Time) *RequestVerificationCreate {
	rvc.mutation.SetUpdatedAt(t)
	return rvc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rvc *RequestVerificationCreate) SetNillableUpdatedAt(t *time.Time) *RequestVerificationCreate {
	if t != nil {
		rvc.SetUpdatedAt(*t)
	}
	return rvc
}

// SetDeletedAt sets the "deleted_at" field.
func (rvc *RequestVerificationCreate) SetDeletedAt(t time.Time) *RequestVerificationCreate {
	rvc.mutation.SetDeletedAt(t)
	return rvc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (rvc *RequestVerificationCreate) SetNillableDeletedAt(t *time.Time) *RequestVerificationCreate {
	if t != nil {
		rvc.SetDeletedAt(*t)
	}
	return rvc
}

// SetReferenceID sets the "reference_id" field.
func (rvc *RequestVerificationCreate) SetReferenceID(s string) *RequestVerificationCreate {
	rvc.mutation.SetReferenceID(s)
	return rvc
}

// SetVerificationType sets the "verification_type" field.
func (rvc *RequestVerificationCreate) SetVerificationType(s string) *RequestVerificationCreate {
	rvc.mutation.SetVerificationType(s)
	return rvc
}

// SetProvider sets the "provider" field.
func (rvc *RequestVerificationCreate) SetProvider(s string) *RequestVerificationCreate {
	rvc.mutation.SetProvider(s)
	return rvc
}

// SetLink sets the "link" field.
func (rvc *RequestVerificationCreate) SetLink(s string) *RequestVerificationCreate {
	rvc.mutation.SetLink(s)
	return rvc
}

// SetProviderLink sets the "provider_link" field.
func (rvc *RequestVerificationCreate) SetProviderLink(s string) *RequestVerificationCreate {
	rvc.mutation.SetProviderLink(s)
	return rvc
}

// SetStatus sets the "status" field.
func (rvc *RequestVerificationCreate) SetStatus(r requestverification.Status) *RequestVerificationCreate {
	rvc.mutation.SetStatus(r)
	return rvc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rvc *RequestVerificationCreate) SetNillableStatus(r *requestverification.Status) *RequestVerificationCreate {
	if r != nil {
		rvc.SetStatus(*r)
	}
	return rvc
}

// SetID sets the "id" field.
func (rvc *RequestVerificationCreate) SetID(s string) *RequestVerificationCreate {
	rvc.mutation.SetID(s)
	return rvc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rvc *RequestVerificationCreate) SetNillableID(s *string) *RequestVerificationCreate {
	if s != nil {
		rvc.SetID(*s)
	}
	return rvc
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (rvc *RequestVerificationCreate) AddUserIDs(ids ...string) *RequestVerificationCreate {
	rvc.mutation.AddUserIDs(ids...)
	return rvc
}

// AddUser adds the "user" edges to the User entity.
func (rvc *RequestVerificationCreate) AddUser(u ...*User) *RequestVerificationCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return rvc.AddUserIDs(ids...)
}

// AddBusinesIDs adds the "business" edge to the Business entity by IDs.
func (rvc *RequestVerificationCreate) AddBusinesIDs(ids ...string) *RequestVerificationCreate {
	rvc.mutation.AddBusinesIDs(ids...)
	return rvc
}

// AddBusiness adds the "business" edges to the Business entity.
func (rvc *RequestVerificationCreate) AddBusiness(b ...*Business) *RequestVerificationCreate {
	ids := make([]string, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return rvc.AddBusinesIDs(ids...)
}

// Mutation returns the RequestVerificationMutation object of the builder.
func (rvc *RequestVerificationCreate) Mutation() *RequestVerificationMutation {
	return rvc.mutation
}

// Save creates the RequestVerification in the database.
func (rvc *RequestVerificationCreate) Save(ctx context.Context) (*RequestVerification, error) {
	rvc.defaults()
	return withHooks(ctx, rvc.sqlSave, rvc.mutation, rvc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rvc *RequestVerificationCreate) SaveX(ctx context.Context) *RequestVerification {
	v, err := rvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rvc *RequestVerificationCreate) Exec(ctx context.Context) error {
	_, err := rvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rvc *RequestVerificationCreate) ExecX(ctx context.Context) {
	if err := rvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rvc *RequestVerificationCreate) defaults() {
	if _, ok := rvc.mutation.CreatedAt(); !ok {
		v := requestverification.DefaultCreatedAt()
		rvc.mutation.SetCreatedAt(v)
	}
	if _, ok := rvc.mutation.UpdatedAt(); !ok {
		v := requestverification.DefaultUpdatedAt()
		rvc.mutation.SetUpdatedAt(v)
	}
	if _, ok := rvc.mutation.Status(); !ok {
		v := requestverification.DefaultStatus
		rvc.mutation.SetStatus(v)
	}
	if _, ok := rvc.mutation.ID(); !ok {
		v := requestverification.DefaultID()
		rvc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rvc *RequestVerificationCreate) check() error {
	if _, ok := rvc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestVerification.created_at"`)}
	}
	if _, ok := rvc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RequestVerification.updated_at"`)}
	}
	if _, ok := rvc.mutation.ReferenceID(); !ok {
		return &ValidationError{Name: "reference_id", err: errors.New(`ent: missing required field "RequestVerification.reference_id"`)}
	}
	if v, ok := rvc.mutation.ReferenceID(); ok {
		if err := requestverification.ReferenceIDValidator(v); err != nil {
			return &ValidationError{Name: "reference_id", err: fmt.Errorf(`ent: validator failed for field "RequestVerification.reference_id": %w`, err)}
		}
	}
	if _, ok := rvc.mutation.VerificationType(); !ok {
		return &ValidationError{Name: "verification_type", err: errors.New(`ent: missing required field "RequestVerification.verification_type"`)}
	}
	if v, ok := rvc.mutation.VerificationType(); ok {
		if err := requestverification.VerificationTypeValidator(v); err != nil {
			return &ValidationError{Name: "verification_type", err: fmt.Errorf(`ent: validator failed for field "RequestVerification.verification_type": %w`, err)}
		}
	}
	if _, ok := rvc.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "RequestVerification.provider"`)}
	}
	if v, ok := rvc.mutation.Provider(); ok {
		if err := requestverification.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "RequestVerification.provider": %w`, err)}
		}
	}
	if _, ok := rvc.mutation.Link(); !ok {
		return &ValidationError{Name: "link", err: errors.New(`ent: missing required field "RequestVerification.link"`)}
	}
	if v, ok := rvc.mutation.Link(); ok {
		if err := requestverification.LinkValidator(v); err != nil {
			return &ValidationError{Name: "link", err: fmt.Errorf(`ent: validator failed for field "RequestVerification.link": %w`, err)}
		}
	}
	if _, ok := rvc.mutation.ProviderLink(); !ok {
		return &ValidationError{Name: "provider_link", err: errors.New(`ent: missing required field "RequestVerification.provider_link"`)}
	}
	if v, ok := rvc.mutation.ProviderLink(); ok {
		if err := requestverification.ProviderLinkValidator(v); err != nil {
			return &ValidationError{Name: "provider_link", err: fmt.Errorf(`ent: validator failed for field "RequestVerification.provider_link": %w`, err)}
		}
	}
	if _, ok := rvc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RequestVerification.status"`)}
	}
	if v, ok := rvc.mutation.Status(); ok {
		if err := requestverification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestVerification.status": %w`, err)}
		}
	}
	return nil
}

func (rvc *RequestVerificationCreate) sqlSave(ctx context.Context) (*RequestVerification, error) {
	if err := rvc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RequestVerification.ID type: %T", _spec.ID.Value)
		}
	}
	rvc.mutation.id = &_node.ID
	rvc.mutation.done = true
	return _node, nil
}

func (rvc *RequestVerificationCreate) createSpec() (*RequestVerification, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestVerification{config: rvc.config}
		_spec = sqlgraph.NewCreateSpec(requestverification.Table, sqlgraph.NewFieldSpec(requestverification.FieldID, field.TypeString))
	)
	_spec.OnConflict = rvc.conflict
	if id, ok := rvc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rvc.mutation.CreatedAt(); ok {
		_spec.SetField(requestverification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rvc.mutation.UpdatedAt(); ok {
		_spec.SetField(requestverification.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := rvc.mutation.DeletedAt(); ok {
		_spec.SetField(requestverification.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := rvc.mutation.ReferenceID(); ok {
		_spec.SetField(requestverification.FieldReferenceID, field.TypeString, value)
		_node.ReferenceID = value
	}
	if value, ok := rvc.mutation.VerificationType(); ok {
		_spec.SetField(requestverification.FieldVerificationType, field.TypeString, value)
		_node.VerificationType = value
	}
	if value, ok := rvc.mutation.Provider(); ok {
		_spec.SetField(requestverification.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := rvc.mutation.Link(); ok {
		_spec.SetField(requestverification.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if value, ok := rvc.mutation.ProviderLink(); ok {
		_spec.SetField(requestverification.FieldProviderLink, field.TypeString, value)
		_node.ProviderLink = value
	}
	if value, ok := rvc.mutation.Status(); ok {
		_spec.SetField(requestverification.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := rvc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   requestverification.UserTable,
			Columns: requestverification.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rvc.mutation.BusinessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   requestverification.BusinessTable,
			Columns: requestverification.BusinessPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestVerification.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestVerificationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (rvc *RequestVerificationCreate) OnConflict(opts ...sql.ConflictOption) *RequestVerificationUpsertOne {
	rvc.conflict = opts
	return &RequestVerificationUpsertOne{
		create: rvc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestVerification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rvc *RequestVerificationCreate) OnConflictColumns(columns ...string) *RequestVerificationUpsertOne {
	rvc.conflict = append(rvc.conflict, sql.ConflictColumns(columns...))
	return &RequestVerificationUpsertOne{
		create: rvc,
	}
}

type (
	// RequestVerificationUpsertOne is the builder for "upsert"-ing
	//  one RequestVerification node.
	RequestVerificationUpsertOne struct {
		create *RequestVerificationCreate
	}

	// RequestVerificationUpsert is the "OnConflict" setter.
	RequestVerificationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestVerificationUpsert) SetUpdatedAt(v time.Time) *RequestVerificationUpsert {
	u.Set(requestverification.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestVerificationUpsert) UpdateUpdatedAt() *RequestVerificationUpsert {
	u.SetExcluded(requestverification.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RequestVerificationUpsert) SetDeletedAt(v time.Time) *RequestVerificationUpsert {
	u.Set(requestverification.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RequestVerificationUpsert) UpdateDeletedAt() *RequestVerificationUpsert {
	u.SetExcluded(requestverification.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RequestVerificationUpsert) ClearDeletedAt() *RequestVerificationUpsert {
	u.SetNull(requestverification.FieldDeletedAt)
	return u
}

// SetReferenceID sets the "reference_id" field.
func (u *RequestVerificationUpsert) SetReferenceID(v string) *RequestVerificationUpsert {
	u.Set(requestverification.FieldReferenceID, v)
	return u
}

// UpdateReferenceID sets the "reference_id" field to the value that was provided on create.
func (u *RequestVerificationUpsert) UpdateReferenceID() *RequestVerificationUpsert {
	u.SetExcluded(requestverification.FieldReferenceID)
	return u
}

// SetVerificationType sets the "verification_type" field.
func (u *RequestVerificationUpsert) SetVerificationType(v string) *RequestVerificationUpsert {
	u.Set(requestverification.FieldVerificationType, v)
	return u
}

// UpdateVerificationType sets the "verification_type" field to the value that was provided on create.
func (u *RequestVerificationUpsert) UpdateVerificationType() *RequestVerificationUpsert {
	u.SetExcluded(requestverification.FieldVerificationType)
	return u
}

// SetProvider sets the "provider" field.
func (u *RequestVerificationUpsert) SetProvider(v string) *RequestVerificationUpsert {
	u.Set(requestverification.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *RequestVerificationUpsert) UpdateProvider() *RequestVerificationUpsert {
	u.SetExcluded(requestverification.FieldProvider)
	return u
}

// SetLink sets the "link" field.
func (u *RequestVerificationUpsert) SetLink(v string) *RequestVerificationUpsert {
	u.Set(requestverification.FieldLink, v)
	return u
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *RequestVerificationUpsert) UpdateLink() *RequestVerificationUpsert {
	u.SetExcluded(requestverification.FieldLink)
	return u
}

// SetProviderLink sets the "provider_link" field.
func (u *RequestVerificationUpsert) SetProviderLink(v string) *RequestVerificationUpsert {
	u.Set(requestverification.FieldProviderLink, v)
	return u
}

// UpdateProviderLink sets the "provider_link" field to the value that was provided on create.
func (u *RequestVerificationUpsert) UpdateProviderLink() *RequestVerificationUpsert {
	u.SetExcluded(requestverification.FieldProviderLink)
	return u
}

// SetStatus sets the "status" field.
func (u *RequestVerificationUpsert) SetStatus(v requestverification.Status) *RequestVerificationUpsert {
	u.Set(requestverification.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestVerificationUpsert) UpdateStatus() *RequestVerificationUpsert {
	u.SetExcluded(requestverification.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RequestVerification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(requestverification.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RequestVerificationUpsertOne) UpdateNewValues() *RequestVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(requestverification.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestverification.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestVerification.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestVerificationUpsertOne) Ignore() *RequestVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestVerificationUpsertOne) DoNothing() *RequestVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestVerificationCreate.OnConflict
// documentation for more info.
func (u *RequestVerificationUpsertOne) Update(set func(*RequestVerificationUpsert)) *RequestVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestVerificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestVerificationUpsertOne) SetUpdatedAt(v time.Time) *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestVerificationUpsertOne) UpdateUpdatedAt() *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RequestVerificationUpsertOne) SetDeletedAt(v time.Time) *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RequestVerificationUpsertOne) UpdateDeletedAt() *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RequestVerificationUpsertOne) ClearDeletedAt() *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetReferenceID sets the "reference_id" field.
func (u *RequestVerificationUpsertOne) SetReferenceID(v string) *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetReferenceID(v)
	})
}

// UpdateReferenceID sets the "reference_id" field to the value that was provided on create.
func (u *RequestVerificationUpsertOne) UpdateReferenceID() *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateReferenceID()
	})
}

// SetVerificationType sets the "verification_type" field.
func (u *RequestVerificationUpsertOne) SetVerificationType(v string) *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetVerificationType(v)
	})
}

// UpdateVerificationType sets the "verification_type" field to the value that was provided on create.
func (u *RequestVerificationUpsertOne) UpdateVerificationType() *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateVerificationType()
	})
}

// SetProvider sets the "provider" field.
func (u *RequestVerificationUpsertOne) SetProvider(v string) *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *RequestVerificationUpsertOne) UpdateProvider() *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateProvider()
	})
}

// SetLink sets the "link" field.
func (u *RequestVerificationUpsertOne) SetLink(v string) *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *RequestVerificationUpsertOne) UpdateLink() *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateLink()
	})
}

// SetProviderLink sets the "provider_link" field.
func (u *RequestVerificationUpsertOne) SetProviderLink(v string) *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetProviderLink(v)
	})
}

// UpdateProviderLink sets the "provider_link" field to the value that was provided on create.
func (u *RequestVerificationUpsertOne) UpdateProviderLink() *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateProviderLink()
	})
}

// SetStatus sets the "status" field.
func (u *RequestVerificationUpsertOne) SetStatus(v requestverification.Status) *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestVerificationUpsertOne) UpdateStatus() *RequestVerificationUpsertOne {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *RequestVerificationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestVerificationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestVerificationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestVerificationUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RequestVerificationUpsertOne.ID is not supported by MySQL driver. Use RequestVerificationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestVerificationUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestVerificationCreateBulk is the builder for creating many RequestVerification entities in bulk.
type RequestVerificationCreateBulk struct {
	config
	err      error
	builders []*RequestVerificationCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestVerification entities in the database.
func (rvcb *RequestVerificationCreateBulk) Save(ctx context.Context) ([]*RequestVerification, error) {
	if rvcb.err != nil {
		return nil, rvcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rvcb.builders))
	nodes := make([]*RequestVerification, len(rvcb.builders))
	mutators := make([]Mutator, len(rvcb.builders))
	for i := range rvcb.builders {
		func(i int, root context.Context) {
			builder := rvcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestVerificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rvcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rvcb *RequestVerificationCreateBulk) SaveX(ctx context.Context) []*RequestVerification {
	v, err := rvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rvcb *RequestVerificationCreateBulk) Exec(ctx context.Context) error {
	_, err := rvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rvcb *RequestVerificationCreateBulk) ExecX(ctx context.Context) {
	if err := rvcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestVerification.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestVerificationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (rvcb *RequestVerificationCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestVerificationUpsertBulk {
	rvcb.conflict = opts
	return &RequestVerificationUpsertBulk{
		create: rvcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestVerification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rvcb *RequestVerificationCreateBulk) OnConflictColumns(columns ...string) *RequestVerificationUpsertBulk {
	rvcb.conflict = append(rvcb.conflict, sql.ConflictColumns(columns...))
	return &RequestVerificationUpsertBulk{
		create: rvcb,
	}
}

// RequestVerificationUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestVerification nodes.
type RequestVerificationUpsertBulk struct {
	create *RequestVerificationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestVerification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(requestverification.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RequestVerificationUpsertBulk) UpdateNewValues() *RequestVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(requestverification.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestverification.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestVerification.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestVerificationUpsertBulk) Ignore() *RequestVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestVerificationUpsertBulk) DoNothing() *RequestVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestVerificationCreateBulk.OnConflict
// documentation for more info.
func (u *RequestVerificationUpsertBulk) Update(set func(*RequestVerificationUpsert)) *RequestVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestVerificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestVerificationUpsertBulk) SetUpdatedAt(v time.Time) *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestVerificationUpsertBulk) UpdateUpdatedAt() *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RequestVerificationUpsertBulk) SetDeletedAt(v time.Time) *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RequestVerificationUpsertBulk) UpdateDeletedAt() *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RequestVerificationUpsertBulk) ClearDeletedAt() *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetReferenceID sets the "reference_id" field.
func (u *RequestVerificationUpsertBulk) SetReferenceID(v string) *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetReferenceID(v)
	})
}

// UpdateReferenceID sets the "reference_id" field to the value that was provided on create.
func (u *RequestVerificationUpsertBulk) UpdateReferenceID() *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateReferenceID()
	})
}

// SetVerificationType sets the "verification_type" field.
func (u *RequestVerificationUpsertBulk) SetVerificationType(v string) *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetVerificationType(v)
	})
}

// UpdateVerificationType sets the "verification_type" field to the value that was provided on create.
func (u *RequestVerificationUpsertBulk) UpdateVerificationType() *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateVerificationType()
	})
}

// SetProvider sets the "provider" field.
func (u *RequestVerificationUpsertBulk) SetProvider(v string) *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *RequestVerificationUpsertBulk) UpdateProvider() *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateProvider()
	})
}

// SetLink sets the "link" field.
func (u *RequestVerificationUpsertBulk) SetLink(v string) *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *RequestVerificationUpsertBulk) UpdateLink() *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateLink()
	})
}

// SetProviderLink sets the "provider_link" field.
func (u *RequestVerificationUpsertBulk) SetProviderLink(v string) *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetProviderLink(v)
	})
}

// UpdateProviderLink sets the "provider_link" field to the value that was provided on create.
func (u *RequestVerificationUpsertBulk) UpdateProviderLink() *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateProviderLink()
	})
}

// SetStatus sets the "status" field.
func (u *RequestVerificationUpsertBulk) SetStatus(v requestverification.Status) *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestVerificationUpsertBulk) UpdateStatus() *RequestVerificationUpsertBulk {
	return u.Update(func(s *RequestVerificationUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *RequestVerificationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestVerificationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestVerificationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestVerificationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
