// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Toflex/directory_v2/ent/business"
	"github.com/Toflex/directory_v2/ent/predicate"
	"github.com/Toflex/directory_v2/ent/social"
)

// SocialUpdate is the builder for updating Social entities.
type SocialUpdate struct {
	config
	hooks    []Hook
	mutation *SocialMutation
}

// Where appends a list predicates to the SocialUpdate builder.
func (su *SocialUpdate) Where(ps ...predicate.Social) *SocialUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SocialUpdate) SetUpdatedAt(t time.Time) *SocialUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetDeletedAt sets the "deleted_at" field.
func (su *SocialUpdate) SetDeletedAt(t time.Time) *SocialUpdate {
	su.mutation.SetDeletedAt(t)
	return su
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (su *SocialUpdate) SetNillableDeletedAt(t *time.Time) *SocialUpdate {
	if t != nil {
		su.SetDeletedAt(*t)
	}
	return su
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (su *SocialUpdate) ClearDeletedAt() *SocialUpdate {
	su.mutation.ClearDeletedAt()
	return su
}

// SetBusinessID sets the "business_id" field.
func (su *SocialUpdate) SetBusinessID(s string) *SocialUpdate {
	su.mutation.SetBusinessID(s)
	return su
}

// SetNillableBusinessID sets the "business_id" field if the given value is not nil.
func (su *SocialUpdate) SetNillableBusinessID(s *string) *SocialUpdate {
	if s != nil {
		su.SetBusinessID(*s)
	}
	return su
}

// SetName sets the "name" field.
func (su *SocialUpdate) SetName(s string) *SocialUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SocialUpdate) SetNillableName(s *string) *SocialUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetURL sets the "url" field.
func (su *SocialUpdate) SetURL(s string) *SocialUpdate {
	su.mutation.SetURL(s)
	return su
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (su *SocialUpdate) SetNillableURL(s *string) *SocialUpdate {
	if s != nil {
		su.SetURL(*s)
	}
	return su
}

// SetSocialID sets the "social" edge to the Business entity by ID.
func (su *SocialUpdate) SetSocialID(id string) *SocialUpdate {
	su.mutation.SetSocialID(id)
	return su
}

// SetSocial sets the "social" edge to the Business entity.
func (su *SocialUpdate) SetSocial(b *Business) *SocialUpdate {
	return su.SetSocialID(b.ID)
}

// Mutation returns the SocialMutation object of the builder.
func (su *SocialUpdate) Mutation() *SocialMutation {
	return su.mutation
}

// ClearSocial clears the "social" edge to the Business entity.
func (su *SocialUpdate) ClearSocial() *SocialUpdate {
	su.mutation.ClearSocial()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SocialUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SocialUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SocialUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SocialUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SocialUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := social.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SocialUpdate) check() error {
	if v, ok := su.mutation.Name(); ok {
		if err := social.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Social.name": %w`, err)}
		}
	}
	if v, ok := su.mutation.URL(); ok {
		if err := social.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Social.url": %w`, err)}
		}
	}
	if su.mutation.SocialCleared() && len(su.mutation.SocialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Social.social"`)
	}
	return nil
}

func (su *SocialUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(social.Table, social.Columns, sqlgraph.NewFieldSpec(social.FieldID, field.TypeString))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(social.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.DeletedAt(); ok {
		_spec.SetField(social.FieldDeletedAt, field.TypeTime, value)
	}
	if su.mutation.DeletedAtCleared() {
		_spec.ClearField(social.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(social.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.URL(); ok {
		_spec.SetField(social.FieldURL, field.TypeString, value)
	}
	if su.mutation.SocialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   social.SocialTable,
			Columns: []string{social.SocialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SocialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   social.SocialTable,
			Columns: []string{social.SocialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{social.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SocialUpdateOne is the builder for updating a single Social entity.
type SocialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SocialMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SocialUpdateOne) SetUpdatedAt(t time.Time) *SocialUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetDeletedAt sets the "deleted_at" field.
func (suo *SocialUpdateOne) SetDeletedAt(t time.Time) *SocialUpdateOne {
	suo.mutation.SetDeletedAt(t)
	return suo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suo *SocialUpdateOne) SetNillableDeletedAt(t *time.Time) *SocialUpdateOne {
	if t != nil {
		suo.SetDeletedAt(*t)
	}
	return suo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suo *SocialUpdateOne) ClearDeletedAt() *SocialUpdateOne {
	suo.mutation.ClearDeletedAt()
	return suo
}

// SetBusinessID sets the "business_id" field.
func (suo *SocialUpdateOne) SetBusinessID(s string) *SocialUpdateOne {
	suo.mutation.SetBusinessID(s)
	return suo
}

// SetNillableBusinessID sets the "business_id" field if the given value is not nil.
func (suo *SocialUpdateOne) SetNillableBusinessID(s *string) *SocialUpdateOne {
	if s != nil {
		suo.SetBusinessID(*s)
	}
	return suo
}

// SetName sets the "name" field.
func (suo *SocialUpdateOne) SetName(s string) *SocialUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SocialUpdateOne) SetNillableName(s *string) *SocialUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetURL sets the "url" field.
func (suo *SocialUpdateOne) SetURL(s string) *SocialUpdateOne {
	suo.mutation.SetURL(s)
	return suo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (suo *SocialUpdateOne) SetNillableURL(s *string) *SocialUpdateOne {
	if s != nil {
		suo.SetURL(*s)
	}
	return suo
}

// SetSocialID sets the "social" edge to the Business entity by ID.
func (suo *SocialUpdateOne) SetSocialID(id string) *SocialUpdateOne {
	suo.mutation.SetSocialID(id)
	return suo
}

// SetSocial sets the "social" edge to the Business entity.
func (suo *SocialUpdateOne) SetSocial(b *Business) *SocialUpdateOne {
	return suo.SetSocialID(b.ID)
}

// Mutation returns the SocialMutation object of the builder.
func (suo *SocialUpdateOne) Mutation() *SocialMutation {
	return suo.mutation
}

// ClearSocial clears the "social" edge to the Business entity.
func (suo *SocialUpdateOne) ClearSocial() *SocialUpdateOne {
	suo.mutation.ClearSocial()
	return suo
}

// Where appends a list predicates to the SocialUpdate builder.
func (suo *SocialUpdateOne) Where(ps ...predicate.Social) *SocialUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SocialUpdateOne) Select(field string, fields ...string) *SocialUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Social entity.
func (suo *SocialUpdateOne) Save(ctx context.Context) (*Social, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SocialUpdateOne) SaveX(ctx context.Context) *Social {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SocialUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SocialUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SocialUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := social.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SocialUpdateOne) check() error {
	if v, ok := suo.mutation.Name(); ok {
		if err := social.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Social.name": %w`, err)}
		}
	}
	if v, ok := suo.mutation.URL(); ok {
		if err := social.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Social.url": %w`, err)}
		}
	}
	if suo.mutation.SocialCleared() && len(suo.mutation.SocialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Social.social"`)
	}
	return nil
}

func (suo *SocialUpdateOne) sqlSave(ctx context.Context) (_node *Social, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(social.Table, social.Columns, sqlgraph.NewFieldSpec(social.FieldID, field.TypeString))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Social.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, social.FieldID)
		for _, f := range fields {
			if !social.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != social.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(social.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.DeletedAt(); ok {
		_spec.SetField(social.FieldDeletedAt, field.TypeTime, value)
	}
	if suo.mutation.DeletedAtCleared() {
		_spec.ClearField(social.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(social.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.URL(); ok {
		_spec.SetField(social.FieldURL, field.TypeString, value)
	}
	if suo.mutation.SocialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   social.SocialTable,
			Columns: []string{social.SocialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SocialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   social.SocialTable,
			Columns: []string{social.SocialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Social{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{social.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
