// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Toflex/directory_v2/ent/predicate"
	"github.com/Toflex/directory_v2/ent/stablecoindeposit"
	"github.com/Toflex/directory_v2/ent/stablecoinwallet"
	"github.com/Toflex/directory_v2/ent/transaction"
)

// StablecoinDepositQuery is the builder for querying StablecoinDeposit entities.
type StablecoinDepositQuery struct {
	config
	ctx                  *QueryContext
	order                []stablecoindeposit.OrderOption
	inters               []Interceptor
	predicates           []predicate.StablecoinDeposit
	withTransaction      *TransactionQuery
	withStablecoinWallet *StablecoinWalletQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StablecoinDepositQuery builder.
func (sdq *StablecoinDepositQuery) Where(ps ...predicate.StablecoinDeposit) *StablecoinDepositQuery {
	sdq.predicates = append(sdq.predicates, ps...)
	return sdq
}

// Limit the number of records to be returned by this query.
func (sdq *StablecoinDepositQuery) Limit(limit int) *StablecoinDepositQuery {
	sdq.ctx.Limit = &limit
	return sdq
}

// Offset to start from.
func (sdq *StablecoinDepositQuery) Offset(offset int) *StablecoinDepositQuery {
	sdq.ctx.Offset = &offset
	return sdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sdq *StablecoinDepositQuery) Unique(unique bool) *StablecoinDepositQuery {
	sdq.ctx.Unique = &unique
	return sdq
}

// Order specifies how the records should be ordered.
func (sdq *StablecoinDepositQuery) Order(o ...stablecoindeposit.OrderOption) *StablecoinDepositQuery {
	sdq.order = append(sdq.order, o...)
	return sdq
}

// QueryTransaction chains the current query on the "transaction" edge.
func (sdq *StablecoinDepositQuery) QueryTransaction() *TransactionQuery {
	query := (&TransactionClient{config: sdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stablecoindeposit.Table, stablecoindeposit.FieldID, selector),
			sqlgraph.To(transaction.Table, transaction.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, stablecoindeposit.TransactionTable, stablecoindeposit.TransactionColumn),
		)
		fromU = sqlgraph.SetNeighbors(sdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStablecoinWallet chains the current query on the "stablecoin_wallet" edge.
func (sdq *StablecoinDepositQuery) QueryStablecoinWallet() *StablecoinWalletQuery {
	query := (&StablecoinWalletClient{config: sdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stablecoindeposit.Table, stablecoindeposit.FieldID, selector),
			sqlgraph.To(stablecoinwallet.Table, stablecoinwallet.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stablecoindeposit.StablecoinWalletTable, stablecoindeposit.StablecoinWalletColumn),
		)
		fromU = sqlgraph.SetNeighbors(sdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StablecoinDeposit entity from the query.
// Returns a *NotFoundError when no StablecoinDeposit was found.
func (sdq *StablecoinDepositQuery) First(ctx context.Context) (*StablecoinDeposit, error) {
	nodes, err := sdq.Limit(1).All(setContextOp(ctx, sdq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stablecoindeposit.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sdq *StablecoinDepositQuery) FirstX(ctx context.Context) *StablecoinDeposit {
	node, err := sdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StablecoinDeposit ID from the query.
// Returns a *NotFoundError when no StablecoinDeposit ID was found.
func (sdq *StablecoinDepositQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sdq.Limit(1).IDs(setContextOp(ctx, sdq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stablecoindeposit.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sdq *StablecoinDepositQuery) FirstIDX(ctx context.Context) string {
	id, err := sdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StablecoinDeposit entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StablecoinDeposit entity is found.
// Returns a *NotFoundError when no StablecoinDeposit entities are found.
func (sdq *StablecoinDepositQuery) Only(ctx context.Context) (*StablecoinDeposit, error) {
	nodes, err := sdq.Limit(2).All(setContextOp(ctx, sdq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stablecoindeposit.Label}
	default:
		return nil, &NotSingularError{stablecoindeposit.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sdq *StablecoinDepositQuery) OnlyX(ctx context.Context) *StablecoinDeposit {
	node, err := sdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StablecoinDeposit ID in the query.
// Returns a *NotSingularError when more than one StablecoinDeposit ID is found.
// Returns a *NotFoundError when no entities are found.
func (sdq *StablecoinDepositQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sdq.Limit(2).IDs(setContextOp(ctx, sdq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stablecoindeposit.Label}
	default:
		err = &NotSingularError{stablecoindeposit.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sdq *StablecoinDepositQuery) OnlyIDX(ctx context.Context) string {
	id, err := sdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StablecoinDeposits.
func (sdq *StablecoinDepositQuery) All(ctx context.Context) ([]*StablecoinDeposit, error) {
	ctx = setContextOp(ctx, sdq.ctx, ent.OpQueryAll)
	if err := sdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StablecoinDeposit, *StablecoinDepositQuery]()
	return withInterceptors[[]*StablecoinDeposit](ctx, sdq, qr, sdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sdq *StablecoinDepositQuery) AllX(ctx context.Context) []*StablecoinDeposit {
	nodes, err := sdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StablecoinDeposit IDs.
func (sdq *StablecoinDepositQuery) IDs(ctx context.Context) (ids []string, err error) {
	if sdq.ctx.Unique == nil && sdq.path != nil {
		sdq.Unique(true)
	}
	ctx = setContextOp(ctx, sdq.ctx, ent.OpQueryIDs)
	if err = sdq.Select(stablecoindeposit.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sdq *StablecoinDepositQuery) IDsX(ctx context.Context) []string {
	ids, err := sdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sdq *StablecoinDepositQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sdq.ctx, ent.OpQueryCount)
	if err := sdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sdq, querierCount[*StablecoinDepositQuery](), sdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sdq *StablecoinDepositQuery) CountX(ctx context.Context) int {
	count, err := sdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sdq *StablecoinDepositQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sdq.ctx, ent.OpQueryExist)
	switch _, err := sdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sdq *StablecoinDepositQuery) ExistX(ctx context.Context) bool {
	exist, err := sdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StablecoinDepositQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sdq *StablecoinDepositQuery) Clone() *StablecoinDepositQuery {
	if sdq == nil {
		return nil
	}
	return &StablecoinDepositQuery{
		config:               sdq.config,
		ctx:                  sdq.ctx.Clone(),
		order:                append([]stablecoindeposit.OrderOption{}, sdq.order...),
		inters:               append([]Interceptor{}, sdq.inters...),
		predicates:           append([]predicate.StablecoinDeposit{}, sdq.predicates...),
		withTransaction:      sdq.withTransaction.Clone(),
		withStablecoinWallet: sdq.withStablecoinWallet.Clone(),
		// clone intermediate query.
		sql:  sdq.sql.Clone(),
		path: sdq.path,
	}
}

// WithTransaction tells the query-builder to eager-load the nodes that are connected to
// the "transaction" edge. The optional arguments are used to configure the query builder of the edge.
func (sdq *StablecoinDepositQuery) WithTransaction(opts ...func(*TransactionQuery)) *StablecoinDepositQuery {
	query := (&TransactionClient{config: sdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sdq.withTransaction = query
	return sdq
}

// WithStablecoinWallet tells the query-builder to eager-load the nodes that are connected to
// the "stablecoin_wallet" edge. The optional arguments are used to configure the query builder of the edge.
func (sdq *StablecoinDepositQuery) WithStablecoinWallet(opts ...func(*StablecoinWalletQuery)) *StablecoinDepositQuery {
	query := (&StablecoinWalletClient{config: sdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sdq.withStablecoinWallet = query
	return sdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StablecoinDeposit.Query().
//		GroupBy(stablecoindeposit.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sdq *StablecoinDepositQuery) GroupBy(field string, fields ...string) *StablecoinDepositGroupBy {
	sdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StablecoinDepositGroupBy{build: sdq}
	grbuild.flds = &sdq.ctx.Fields
	grbuild.label = stablecoindeposit.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.StablecoinDeposit.Query().
//		Select(stablecoindeposit.FieldCreatedAt).
//		Scan(ctx, &v)
func (sdq *StablecoinDepositQuery) Select(fields ...string) *StablecoinDepositSelect {
	sdq.ctx.Fields = append(sdq.ctx.Fields, fields...)
	sbuild := &StablecoinDepositSelect{StablecoinDepositQuery: sdq}
	sbuild.label = stablecoindeposit.Label
	sbuild.flds, sbuild.scan = &sdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StablecoinDepositSelect configured with the given aggregations.
func (sdq *StablecoinDepositQuery) Aggregate(fns ...AggregateFunc) *StablecoinDepositSelect {
	return sdq.Select().Aggregate(fns...)
}

func (sdq *StablecoinDepositQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sdq); err != nil {
				return err
			}
		}
	}
	for _, f := range sdq.ctx.Fields {
		if !stablecoindeposit.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sdq.path != nil {
		prev, err := sdq.path(ctx)
		if err != nil {
			return err
		}
		sdq.sql = prev
	}
	return nil
}

func (sdq *StablecoinDepositQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StablecoinDeposit, error) {
	var (
		nodes       = []*StablecoinDeposit{}
		_spec       = sdq.querySpec()
		loadedTypes = [2]bool{
			sdq.withTransaction != nil,
			sdq.withStablecoinWallet != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StablecoinDeposit).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StablecoinDeposit{config: sdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sdq.withTransaction; query != nil {
		if err := sdq.loadTransaction(ctx, query, nodes, nil,
			func(n *StablecoinDeposit, e *Transaction) { n.Edges.Transaction = e }); err != nil {
			return nil, err
		}
	}
	if query := sdq.withStablecoinWallet; query != nil {
		if err := sdq.loadStablecoinWallet(ctx, query, nodes, nil,
			func(n *StablecoinDeposit, e *StablecoinWallet) { n.Edges.StablecoinWallet = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sdq *StablecoinDepositQuery) loadTransaction(ctx context.Context, query *TransactionQuery, nodes []*StablecoinDeposit, init func(*StablecoinDeposit), assign func(*StablecoinDeposit, *Transaction)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*StablecoinDeposit)
	for i := range nodes {
		fk := nodes[i].TransactionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(transaction.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "transaction_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (sdq *StablecoinDepositQuery) loadStablecoinWallet(ctx context.Context, query *StablecoinWalletQuery, nodes []*StablecoinDeposit, init func(*StablecoinDeposit), assign func(*StablecoinDeposit, *StablecoinWallet)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*StablecoinDeposit)
	for i := range nodes {
		fk := nodes[i].StablecoinWalletID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(stablecoinwallet.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "stablecoin_wallet_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sdq *StablecoinDepositQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sdq.querySpec()
	_spec.Node.Columns = sdq.ctx.Fields
	if len(sdq.ctx.Fields) > 0 {
		_spec.Unique = sdq.ctx.Unique != nil && *sdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sdq.driver, _spec)
}

func (sdq *StablecoinDepositQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stablecoindeposit.Table, stablecoindeposit.Columns, sqlgraph.NewFieldSpec(stablecoindeposit.FieldID, field.TypeString))
	_spec.From = sdq.sql
	if unique := sdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sdq.path != nil {
		_spec.Unique = true
	}
	if fields := sdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stablecoindeposit.FieldID)
		for i := range fields {
			if fields[i] != stablecoindeposit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if sdq.withTransaction != nil {
			_spec.Node.AddColumnOnce(stablecoindeposit.FieldTransactionID)
		}
		if sdq.withStablecoinWallet != nil {
			_spec.Node.AddColumnOnce(stablecoindeposit.FieldStablecoinWalletID)
		}
	}
	if ps := sdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sdq *StablecoinDepositQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sdq.driver.Dialect())
	t1 := builder.Table(stablecoindeposit.Table)
	columns := sdq.ctx.Fields
	if len(columns) == 0 {
		columns = stablecoindeposit.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sdq.sql != nil {
		selector = sdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sdq.ctx.Unique != nil && *sdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sdq.predicates {
		p(selector)
	}
	for _, p := range sdq.order {
		p(selector)
	}
	if offset := sdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StablecoinDepositGroupBy is the group-by builder for StablecoinDeposit entities.
type StablecoinDepositGroupBy struct {
	selector
	build *StablecoinDepositQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sdgb *StablecoinDepositGroupBy) Aggregate(fns ...AggregateFunc) *StablecoinDepositGroupBy {
	sdgb.fns = append(sdgb.fns, fns...)
	return sdgb
}

// Scan applies the selector query and scans the result into the given value.
func (sdgb *StablecoinDepositGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sdgb.build.ctx, ent.OpQueryGroupBy)
	if err := sdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StablecoinDepositQuery, *StablecoinDepositGroupBy](ctx, sdgb.build, sdgb, sdgb.build.inters, v)
}

func (sdgb *StablecoinDepositGroupBy) sqlScan(ctx context.Context, root *StablecoinDepositQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sdgb.fns))
	for _, fn := range sdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sdgb.flds)+len(sdgb.fns))
		for _, f := range *sdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StablecoinDepositSelect is the builder for selecting fields of StablecoinDeposit entities.
type StablecoinDepositSelect struct {
	*StablecoinDepositQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sds *StablecoinDepositSelect) Aggregate(fns ...AggregateFunc) *StablecoinDepositSelect {
	sds.fns = append(sds.fns, fns...)
	return sds
}

// Scan applies the selector query and scans the result into the given value.
func (sds *StablecoinDepositSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sds.ctx, ent.OpQuerySelect)
	if err := sds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StablecoinDepositQuery, *StablecoinDepositSelect](ctx, sds.StablecoinDepositQuery, sds, sds.inters, v)
}

func (sds *StablecoinDepositSelect) sqlScan(ctx context.Context, root *StablecoinDepositQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sds.fns))
	for _, fn := range sds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
