// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Toflex/directory_v2/ent/predicate"
	"github.com/Toflex/directory_v2/ent/stablecoinnetwork"
	"github.com/Toflex/directory_v2/ent/stablecoinsupportednetwork"
	"github.com/Toflex/directory_v2/ent/stablecoinwallet"
)

// StablecoinNetworkUpdate is the builder for updating StablecoinNetwork entities.
type StablecoinNetworkUpdate struct {
	config
	hooks    []Hook
	mutation *StablecoinNetworkMutation
}

// Where appends a list predicates to the StablecoinNetworkUpdate builder.
func (snu *StablecoinNetworkUpdate) Where(ps ...predicate.StablecoinNetwork) *StablecoinNetworkUpdate {
	snu.mutation.Where(ps...)
	return snu
}

// SetUpdatedAt sets the "updated_at" field.
func (snu *StablecoinNetworkUpdate) SetUpdatedAt(t time.Time) *StablecoinNetworkUpdate {
	snu.mutation.SetUpdatedAt(t)
	return snu
}

// SetDeletedAt sets the "deleted_at" field.
func (snu *StablecoinNetworkUpdate) SetDeletedAt(t time.Time) *StablecoinNetworkUpdate {
	snu.mutation.SetDeletedAt(t)
	return snu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (snu *StablecoinNetworkUpdate) SetNillableDeletedAt(t *time.Time) *StablecoinNetworkUpdate {
	if t != nil {
		snu.SetDeletedAt(*t)
	}
	return snu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (snu *StablecoinNetworkUpdate) ClearDeletedAt() *StablecoinNetworkUpdate {
	snu.mutation.ClearDeletedAt()
	return snu
}

// SetName sets the "name" field.
func (snu *StablecoinNetworkUpdate) SetName(s string) *StablecoinNetworkUpdate {
	snu.mutation.SetName(s)
	return snu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (snu *StablecoinNetworkUpdate) SetNillableName(s *string) *StablecoinNetworkUpdate {
	if s != nil {
		snu.SetName(*s)
	}
	return snu
}

// SetSlug sets the "slug" field.
func (snu *StablecoinNetworkUpdate) SetSlug(s string) *StablecoinNetworkUpdate {
	snu.mutation.SetSlug(s)
	return snu
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (snu *StablecoinNetworkUpdate) SetNillableSlug(s *string) *StablecoinNetworkUpdate {
	if s != nil {
		snu.SetSlug(*s)
	}
	return snu
}

// SetLogoURL sets the "logo_url" field.
func (snu *StablecoinNetworkUpdate) SetLogoURL(s string) *StablecoinNetworkUpdate {
	snu.mutation.SetLogoURL(s)
	return snu
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (snu *StablecoinNetworkUpdate) SetNillableLogoURL(s *string) *StablecoinNetworkUpdate {
	if s != nil {
		snu.SetLogoURL(*s)
	}
	return snu
}

// SetActive sets the "active" field.
func (snu *StablecoinNetworkUpdate) SetActive(b bool) *StablecoinNetworkUpdate {
	snu.mutation.SetActive(b)
	return snu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (snu *StablecoinNetworkUpdate) SetNillableActive(b *bool) *StablecoinNetworkUpdate {
	if b != nil {
		snu.SetActive(*b)
	}
	return snu
}

// AddStablecoinNetworkIDs adds the "stablecoin_networks" edge to the StablecoinWallet entity by IDs.
func (snu *StablecoinNetworkUpdate) AddStablecoinNetworkIDs(ids ...string) *StablecoinNetworkUpdate {
	snu.mutation.AddStablecoinNetworkIDs(ids...)
	return snu
}

// AddStablecoinNetworks adds the "stablecoin_networks" edges to the StablecoinWallet entity.
func (snu *StablecoinNetworkUpdate) AddStablecoinNetworks(s ...*StablecoinWallet) *StablecoinNetworkUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return snu.AddStablecoinNetworkIDs(ids...)
}

// AddStablecoinSupportedNetworkIDs adds the "stablecoin_supported_networks" edge to the StablecoinSupportedNetwork entity by IDs.
func (snu *StablecoinNetworkUpdate) AddStablecoinSupportedNetworkIDs(ids ...string) *StablecoinNetworkUpdate {
	snu.mutation.AddStablecoinSupportedNetworkIDs(ids...)
	return snu
}

// AddStablecoinSupportedNetworks adds the "stablecoin_supported_networks" edges to the StablecoinSupportedNetwork entity.
func (snu *StablecoinNetworkUpdate) AddStablecoinSupportedNetworks(s ...*StablecoinSupportedNetwork) *StablecoinNetworkUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return snu.AddStablecoinSupportedNetworkIDs(ids...)
}

// Mutation returns the StablecoinNetworkMutation object of the builder.
func (snu *StablecoinNetworkUpdate) Mutation() *StablecoinNetworkMutation {
	return snu.mutation
}

// ClearStablecoinNetworks clears all "stablecoin_networks" edges to the StablecoinWallet entity.
func (snu *StablecoinNetworkUpdate) ClearStablecoinNetworks() *StablecoinNetworkUpdate {
	snu.mutation.ClearStablecoinNetworks()
	return snu
}

// RemoveStablecoinNetworkIDs removes the "stablecoin_networks" edge to StablecoinWallet entities by IDs.
func (snu *StablecoinNetworkUpdate) RemoveStablecoinNetworkIDs(ids ...string) *StablecoinNetworkUpdate {
	snu.mutation.RemoveStablecoinNetworkIDs(ids...)
	return snu
}

// RemoveStablecoinNetworks removes "stablecoin_networks" edges to StablecoinWallet entities.
func (snu *StablecoinNetworkUpdate) RemoveStablecoinNetworks(s ...*StablecoinWallet) *StablecoinNetworkUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return snu.RemoveStablecoinNetworkIDs(ids...)
}

// ClearStablecoinSupportedNetworks clears all "stablecoin_supported_networks" edges to the StablecoinSupportedNetwork entity.
func (snu *StablecoinNetworkUpdate) ClearStablecoinSupportedNetworks() *StablecoinNetworkUpdate {
	snu.mutation.ClearStablecoinSupportedNetworks()
	return snu
}

// RemoveStablecoinSupportedNetworkIDs removes the "stablecoin_supported_networks" edge to StablecoinSupportedNetwork entities by IDs.
func (snu *StablecoinNetworkUpdate) RemoveStablecoinSupportedNetworkIDs(ids ...string) *StablecoinNetworkUpdate {
	snu.mutation.RemoveStablecoinSupportedNetworkIDs(ids...)
	return snu
}

// RemoveStablecoinSupportedNetworks removes "stablecoin_supported_networks" edges to StablecoinSupportedNetwork entities.
func (snu *StablecoinNetworkUpdate) RemoveStablecoinSupportedNetworks(s ...*StablecoinSupportedNetwork) *StablecoinNetworkUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return snu.RemoveStablecoinSupportedNetworkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (snu *StablecoinNetworkUpdate) Save(ctx context.Context) (int, error) {
	snu.defaults()
	return withHooks(ctx, snu.sqlSave, snu.mutation, snu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (snu *StablecoinNetworkUpdate) SaveX(ctx context.Context) int {
	affected, err := snu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (snu *StablecoinNetworkUpdate) Exec(ctx context.Context) error {
	_, err := snu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (snu *StablecoinNetworkUpdate) ExecX(ctx context.Context) {
	if err := snu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (snu *StablecoinNetworkUpdate) defaults() {
	if _, ok := snu.mutation.UpdatedAt(); !ok {
		v := stablecoinnetwork.UpdateDefaultUpdatedAt()
		snu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (snu *StablecoinNetworkUpdate) check() error {
	if v, ok := snu.mutation.Name(); ok {
		if err := stablecoinnetwork.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StablecoinNetwork.name": %w`, err)}
		}
	}
	if v, ok := snu.mutation.Slug(); ok {
		if err := stablecoinnetwork.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "StablecoinNetwork.slug": %w`, err)}
		}
	}
	return nil
}

func (snu *StablecoinNetworkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := snu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(stablecoinnetwork.Table, stablecoinnetwork.Columns, sqlgraph.NewFieldSpec(stablecoinnetwork.FieldID, field.TypeString))
	if ps := snu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := snu.mutation.UpdatedAt(); ok {
		_spec.SetField(stablecoinnetwork.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := snu.mutation.DeletedAt(); ok {
		_spec.SetField(stablecoinnetwork.FieldDeletedAt, field.TypeTime, value)
	}
	if snu.mutation.DeletedAtCleared() {
		_spec.ClearField(stablecoinnetwork.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := snu.mutation.Name(); ok {
		_spec.SetField(stablecoinnetwork.FieldName, field.TypeString, value)
	}
	if value, ok := snu.mutation.Slug(); ok {
		_spec.SetField(stablecoinnetwork.FieldSlug, field.TypeString, value)
	}
	if value, ok := snu.mutation.LogoURL(); ok {
		_spec.SetField(stablecoinnetwork.FieldLogoURL, field.TypeString, value)
	}
	if value, ok := snu.mutation.Active(); ok {
		_spec.SetField(stablecoinnetwork.FieldActive, field.TypeBool, value)
	}
	if snu.mutation.StablecoinNetworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinwallet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := snu.mutation.RemovedStablecoinNetworksIDs(); len(nodes) > 0 && !snu.mutation.StablecoinNetworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinwallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := snu.mutation.StablecoinNetworksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinwallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if snu.mutation.StablecoinSupportedNetworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinSupportedNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinSupportedNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinsupportednetwork.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := snu.mutation.RemovedStablecoinSupportedNetworksIDs(); len(nodes) > 0 && !snu.mutation.StablecoinSupportedNetworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinSupportedNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinSupportedNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinsupportednetwork.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := snu.mutation.StablecoinSupportedNetworksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinSupportedNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinSupportedNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinsupportednetwork.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, snu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stablecoinnetwork.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	snu.mutation.done = true
	return n, nil
}

// StablecoinNetworkUpdateOne is the builder for updating a single StablecoinNetwork entity.
type StablecoinNetworkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StablecoinNetworkMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (snuo *StablecoinNetworkUpdateOne) SetUpdatedAt(t time.Time) *StablecoinNetworkUpdateOne {
	snuo.mutation.SetUpdatedAt(t)
	return snuo
}

// SetDeletedAt sets the "deleted_at" field.
func (snuo *StablecoinNetworkUpdateOne) SetDeletedAt(t time.Time) *StablecoinNetworkUpdateOne {
	snuo.mutation.SetDeletedAt(t)
	return snuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (snuo *StablecoinNetworkUpdateOne) SetNillableDeletedAt(t *time.Time) *StablecoinNetworkUpdateOne {
	if t != nil {
		snuo.SetDeletedAt(*t)
	}
	return snuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (snuo *StablecoinNetworkUpdateOne) ClearDeletedAt() *StablecoinNetworkUpdateOne {
	snuo.mutation.ClearDeletedAt()
	return snuo
}

// SetName sets the "name" field.
func (snuo *StablecoinNetworkUpdateOne) SetName(s string) *StablecoinNetworkUpdateOne {
	snuo.mutation.SetName(s)
	return snuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (snuo *StablecoinNetworkUpdateOne) SetNillableName(s *string) *StablecoinNetworkUpdateOne {
	if s != nil {
		snuo.SetName(*s)
	}
	return snuo
}

// SetSlug sets the "slug" field.
func (snuo *StablecoinNetworkUpdateOne) SetSlug(s string) *StablecoinNetworkUpdateOne {
	snuo.mutation.SetSlug(s)
	return snuo
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (snuo *StablecoinNetworkUpdateOne) SetNillableSlug(s *string) *StablecoinNetworkUpdateOne {
	if s != nil {
		snuo.SetSlug(*s)
	}
	return snuo
}

// SetLogoURL sets the "logo_url" field.
func (snuo *StablecoinNetworkUpdateOne) SetLogoURL(s string) *StablecoinNetworkUpdateOne {
	snuo.mutation.SetLogoURL(s)
	return snuo
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (snuo *StablecoinNetworkUpdateOne) SetNillableLogoURL(s *string) *StablecoinNetworkUpdateOne {
	if s != nil {
		snuo.SetLogoURL(*s)
	}
	return snuo
}

// SetActive sets the "active" field.
func (snuo *StablecoinNetworkUpdateOne) SetActive(b bool) *StablecoinNetworkUpdateOne {
	snuo.mutation.SetActive(b)
	return snuo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (snuo *StablecoinNetworkUpdateOne) SetNillableActive(b *bool) *StablecoinNetworkUpdateOne {
	if b != nil {
		snuo.SetActive(*b)
	}
	return snuo
}

// AddStablecoinNetworkIDs adds the "stablecoin_networks" edge to the StablecoinWallet entity by IDs.
func (snuo *StablecoinNetworkUpdateOne) AddStablecoinNetworkIDs(ids ...string) *StablecoinNetworkUpdateOne {
	snuo.mutation.AddStablecoinNetworkIDs(ids...)
	return snuo
}

// AddStablecoinNetworks adds the "stablecoin_networks" edges to the StablecoinWallet entity.
func (snuo *StablecoinNetworkUpdateOne) AddStablecoinNetworks(s ...*StablecoinWallet) *StablecoinNetworkUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return snuo.AddStablecoinNetworkIDs(ids...)
}

// AddStablecoinSupportedNetworkIDs adds the "stablecoin_supported_networks" edge to the StablecoinSupportedNetwork entity by IDs.
func (snuo *StablecoinNetworkUpdateOne) AddStablecoinSupportedNetworkIDs(ids ...string) *StablecoinNetworkUpdateOne {
	snuo.mutation.AddStablecoinSupportedNetworkIDs(ids...)
	return snuo
}

// AddStablecoinSupportedNetworks adds the "stablecoin_supported_networks" edges to the StablecoinSupportedNetwork entity.
func (snuo *StablecoinNetworkUpdateOne) AddStablecoinSupportedNetworks(s ...*StablecoinSupportedNetwork) *StablecoinNetworkUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return snuo.AddStablecoinSupportedNetworkIDs(ids...)
}

// Mutation returns the StablecoinNetworkMutation object of the builder.
func (snuo *StablecoinNetworkUpdateOne) Mutation() *StablecoinNetworkMutation {
	return snuo.mutation
}

// ClearStablecoinNetworks clears all "stablecoin_networks" edges to the StablecoinWallet entity.
func (snuo *StablecoinNetworkUpdateOne) ClearStablecoinNetworks() *StablecoinNetworkUpdateOne {
	snuo.mutation.ClearStablecoinNetworks()
	return snuo
}

// RemoveStablecoinNetworkIDs removes the "stablecoin_networks" edge to StablecoinWallet entities by IDs.
func (snuo *StablecoinNetworkUpdateOne) RemoveStablecoinNetworkIDs(ids ...string) *StablecoinNetworkUpdateOne {
	snuo.mutation.RemoveStablecoinNetworkIDs(ids...)
	return snuo
}

// RemoveStablecoinNetworks removes "stablecoin_networks" edges to StablecoinWallet entities.
func (snuo *StablecoinNetworkUpdateOne) RemoveStablecoinNetworks(s ...*StablecoinWallet) *StablecoinNetworkUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return snuo.RemoveStablecoinNetworkIDs(ids...)
}

// ClearStablecoinSupportedNetworks clears all "stablecoin_supported_networks" edges to the StablecoinSupportedNetwork entity.
func (snuo *StablecoinNetworkUpdateOne) ClearStablecoinSupportedNetworks() *StablecoinNetworkUpdateOne {
	snuo.mutation.ClearStablecoinSupportedNetworks()
	return snuo
}

// RemoveStablecoinSupportedNetworkIDs removes the "stablecoin_supported_networks" edge to StablecoinSupportedNetwork entities by IDs.
func (snuo *StablecoinNetworkUpdateOne) RemoveStablecoinSupportedNetworkIDs(ids ...string) *StablecoinNetworkUpdateOne {
	snuo.mutation.RemoveStablecoinSupportedNetworkIDs(ids...)
	return snuo
}

// RemoveStablecoinSupportedNetworks removes "stablecoin_supported_networks" edges to StablecoinSupportedNetwork entities.
func (snuo *StablecoinNetworkUpdateOne) RemoveStablecoinSupportedNetworks(s ...*StablecoinSupportedNetwork) *StablecoinNetworkUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return snuo.RemoveStablecoinSupportedNetworkIDs(ids...)
}

// Where appends a list predicates to the StablecoinNetworkUpdate builder.
func (snuo *StablecoinNetworkUpdateOne) Where(ps ...predicate.StablecoinNetwork) *StablecoinNetworkUpdateOne {
	snuo.mutation.Where(ps...)
	return snuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (snuo *StablecoinNetworkUpdateOne) Select(field string, fields ...string) *StablecoinNetworkUpdateOne {
	snuo.fields = append([]string{field}, fields...)
	return snuo
}

// Save executes the query and returns the updated StablecoinNetwork entity.
func (snuo *StablecoinNetworkUpdateOne) Save(ctx context.Context) (*StablecoinNetwork, error) {
	snuo.defaults()
	return withHooks(ctx, snuo.sqlSave, snuo.mutation, snuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (snuo *StablecoinNetworkUpdateOne) SaveX(ctx context.Context) *StablecoinNetwork {
	node, err := snuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (snuo *StablecoinNetworkUpdateOne) Exec(ctx context.Context) error {
	_, err := snuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (snuo *StablecoinNetworkUpdateOne) ExecX(ctx context.Context) {
	if err := snuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (snuo *StablecoinNetworkUpdateOne) defaults() {
	if _, ok := snuo.mutation.UpdatedAt(); !ok {
		v := stablecoinnetwork.UpdateDefaultUpdatedAt()
		snuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (snuo *StablecoinNetworkUpdateOne) check() error {
	if v, ok := snuo.mutation.Name(); ok {
		if err := stablecoinnetwork.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StablecoinNetwork.name": %w`, err)}
		}
	}
	if v, ok := snuo.mutation.Slug(); ok {
		if err := stablecoinnetwork.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "StablecoinNetwork.slug": %w`, err)}
		}
	}
	return nil
}

func (snuo *StablecoinNetworkUpdateOne) sqlSave(ctx context.Context) (_node *StablecoinNetwork, err error) {
	if err := snuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stablecoinnetwork.Table, stablecoinnetwork.Columns, sqlgraph.NewFieldSpec(stablecoinnetwork.FieldID, field.TypeString))
	id, ok := snuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StablecoinNetwork.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := snuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stablecoinnetwork.FieldID)
		for _, f := range fields {
			if !stablecoinnetwork.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stablecoinnetwork.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := snuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := snuo.mutation.UpdatedAt(); ok {
		_spec.SetField(stablecoinnetwork.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := snuo.mutation.DeletedAt(); ok {
		_spec.SetField(stablecoinnetwork.FieldDeletedAt, field.TypeTime, value)
	}
	if snuo.mutation.DeletedAtCleared() {
		_spec.ClearField(stablecoinnetwork.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := snuo.mutation.Name(); ok {
		_spec.SetField(stablecoinnetwork.FieldName, field.TypeString, value)
	}
	if value, ok := snuo.mutation.Slug(); ok {
		_spec.SetField(stablecoinnetwork.FieldSlug, field.TypeString, value)
	}
	if value, ok := snuo.mutation.LogoURL(); ok {
		_spec.SetField(stablecoinnetwork.FieldLogoURL, field.TypeString, value)
	}
	if value, ok := snuo.mutation.Active(); ok {
		_spec.SetField(stablecoinnetwork.FieldActive, field.TypeBool, value)
	}
	if snuo.mutation.StablecoinNetworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinwallet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := snuo.mutation.RemovedStablecoinNetworksIDs(); len(nodes) > 0 && !snuo.mutation.StablecoinNetworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinwallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := snuo.mutation.StablecoinNetworksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinwallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if snuo.mutation.StablecoinSupportedNetworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinSupportedNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinSupportedNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinsupportednetwork.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := snuo.mutation.RemovedStablecoinSupportedNetworksIDs(); len(nodes) > 0 && !snuo.mutation.StablecoinSupportedNetworksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinSupportedNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinSupportedNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinsupportednetwork.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := snuo.mutation.StablecoinSupportedNetworksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stablecoinnetwork.StablecoinSupportedNetworksTable,
			Columns: []string{stablecoinnetwork.StablecoinSupportedNetworksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stablecoinsupportednetwork.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StablecoinNetwork{config: snuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, snuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stablecoinnetwork.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	snuo.mutation.done = true
	return _node, nil
}
