-- Modify "businesses" table
ALTER TABLE "businesses" ADD COLUMN "about" character varying NULL, ADD COLUMN "active" boolean NOT NULL DEFAULT false;
-- Modify "services" table
ALTER TABLE "services" ADD COLUMN "provider" character varying NOT NULL;
-- Create index "services_provider_key" to table: "services"
CREATE UNIQUE INDEX "services_provider_key" ON "services" ("provider");
-- Modify "users" table
ALTER TABLE "users" DROP COLUMN "tier", ADD COLUMN "disable_reason" boolean NULL, ADD COLUMN "verified" boolean NOT NULL DEFAULT false;
-- Create "providers" table
CREATE TABLE "providers" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "slug" character varying NOT NULL,
  "active" boolean NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "providers_name_key" to table: "providers"
CREATE UNIQUE INDEX "providers_name_key" ON "providers" ("name");
-- Create index "providers_slug_key" to table: "providers"
CREATE UNIQUE INDEX "providers_slug_key" ON "providers" ("slug");
-- Create "business_services" table
CREATE TABLE "business_services" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "description" character varying NOT NULL,
  "business_id" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "business_services_businesses_services" FOREIGN KEY ("business_id") REFERENCES "businesses" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
